#!/usr/bin/env python3
"""Replace emergency scene with high-quality 100-line dialogue."""
import re

with open("lib/data.ts", "r", encoding="utf-8") as f:
    content = f.read()

EMERGENCY_SCENE = """  emergency: [
    { id: "emergency-1", speaker: "Caller", text: "Hello, I need help with an emergency.", translation: "你好，我遇到了紧急情况，需要帮助。", note: "直接说明紧急情况。" },
    { id: "emergency-2", speaker: "Operator", text: "Tell me your location first, please.", translation: "请先告诉我你的位置。", note: "location 是位置。" },
    { id: "emergency-3", speaker: "Caller", text: "I am outside the central train station.", translation: "我在中央火车站外面。", note: "outside 说明在外部。" },
    { id: "emergency-4", speaker: "Operator", text: "What kind of emergency are you reporting?", translation: "你报告的是什么紧急情况？", note: "report an emergency 表示报告紧急情况。" },
    { id: "emergency-5", speaker: "Caller", text: "There is a car accident with injuries.", translation: "有一场车祸，有人受伤。", note: "car accident with injuries 表示车祸受伤。" },
    { id: "emergency-6", speaker: "Operator", text: "How many people are injured?", translation: "有多少人受伤？", note: "询问受伤人数。" },
    { id: "emergency-7", speaker: "Caller", text: "I see two people trapped in the vehicle.", translation: "我看到两个人被困在车里。", note: "trapped in the vehicle 表示被困。" },
    { id: "emergency-8", speaker: "Operator", text: "Are they conscious and breathing?", translation: "他们有意识且在呼吸吗？", note: "conscious and breathing 表示有意识且呼吸。" },
    { id: "emergency-9", speaker: "Caller", text: "One person is conscious, the other is not.", translation: "一个人有意识，另一个没有。", note: "描述伤者状态。" },
    { id: "emergency-10", speaker: "Operator", text: "Stay on the line. I am dispatching an ambulance now.", translation: "不要挂断。我正在派救护车。", note: "dispatching an ambulance 表示派救护车。" },
    { id: "emergency-11", speaker: "Caller", text: "Thank you. How long will it take?", translation: "谢谢。要多久？", note: "询问等待时间。" },
    { id: "emergency-12", speaker: "Operator", text: "Approximately eight minutes. Stay safe.", translation: "大约8分钟。保持安全。", note: "告知预计时间。" },
    { id: "emergency-13", speaker: "Caller", text: "Okay. I will try to help the injured.", translation: "好的。我会尽力帮助伤者。", note: "表示愿意帮助。" },
    { id: "emergency-14", speaker: "Operator", text: "Do not move them unless there is immediate danger.", translation: "除非有直接危险，否则不要移动他们。", note: "不要随意移动伤者。" },
    { id: "emergency-15", speaker: "Caller", text: "Understood. I will wait for the paramedics.", translation: "明白了。我会等急救人员。", note: "表示理解。" },
    { id: "emergency-16", speaker: "Operator", text: "Good. Can you describe the vehicle?", translation: "好的。能描述一下车辆吗？", note: "询问车辆信息。" },
    { id: "emergency-17", speaker: "Caller", text: "It is a blue sedan with damage to the front.", translation: "是一辆蓝色轿车，前部损坏。", note: "描述车辆。" },
    { id: "emergency-18", speaker: "Operator", text: "Is there any risk of fire?", translation: "有起火风险吗？", note: "询问起火风险。" },
    { id: "emergency-19", speaker: "Caller", text: "No, but there is fluid leaking.", translation: "没有，但有液体泄漏。", note: "描述泄漏情况。" },
    { id: "emergency-20", speaker: "Operator", text: "Be careful. Help is on the way.", translation: "小心。救援在路上。", note: "告知救援在路上。" },
    { id: "emergency-21", speaker: "Caller", text: "Thank you. I will stay with them.", translation: "谢谢。我会陪在他们身边。", note: "表示陪伴。" },
    { id: "emergency-22", speaker: "Operator", text: "You are doing well. Stay calm.", translation: "你做得很好。保持冷静。", note: "鼓励保持冷静。" },
    { id: "emergency-23", speaker: "Caller", text: "I am trying to stay calm.", translation: "我在努力保持冷静。", note: "表示努力。" },
    { id: "emergency-24", speaker: "Operator", text: "Good. Is anyone else at the scene?", translation: "好的。现场还有其他人吗？", note: "询问现场情况。" },
    { id: "emergency-25", speaker: "Caller", text: "Yes, a passerby is helping.", translation: "是的，有路人正在帮忙。", note: "描述现场情况。" },
    { id: "emergency-26", speaker: "Operator", text: "Great. Let them know help is coming.", translation: "太好了。让他们知道救援来了。", note: "告知路人。" },
    { id: "emergency-27", speaker: "Caller", text: "I will tell them. Thank you.", translation: "我会的。谢谢。", note: "表示感谢。" },
    { id: "emergency-28", speaker: "Operator", text: "You are welcome. Stay on the line.", translation: "不客气。保持通话。", note: "提醒保持通话。" },
    { id: "emergency-29", speaker: "Caller", text: "Okay. I am still here.", translation: "好的。我还在。", note: "确认状态。" },
    { id: "emergency-30", speaker: "Operator", text: "Good. The ambulance is five minutes away.", translation: "好的。救护车还有5分钟到。", note: "告知救护车时间。" },
    { id: "emergency-31", speaker: "Caller", text: "Thank you. I will guide them when they arrive.", translation: "谢谢。他们到了我会指引。", note: "表示指引。" },
    { id: "emergency-32", speaker: "Operator", text: "Perfect. Stay where you are.", translation: "完美。待在原地。", note: "提醒待在原地。" },
    { id: "emergency-33", speaker: "Caller", text: "I will. Goodbye for now.", translation: "我会的。暂时再见。", note: "告别。" },
    { id: "emergency-34", speaker: "Operator", text: "Goodbye. Help is coming.", translation: "再见。救援来了。", note: "回应告别。" },
    { id: "emergency-35", speaker: "Caller", text: "Cheers.", translation: "再见。", note: "致意。" },
    { id: "emergency-36", speaker: "Operator", text: "Cheers.", translation: "再见。", note: "回礼。" },
    { id: "emergency-37", speaker: "Caller", text: "Bye!", translation: "拜！", note: "告别。" },
    { id: "emergency-38", speaker: "Operator", text: "Bye!", translation: "拜！", note: "回应。" },
    { id: "emergency-39", speaker: "Caller", text: "See you.", translation: "再见。", note: "道别。" },
    { id: "emergency-40", speaker: "Operator", text: "See you.", translation: "再见。", note: "回应。" },
    { id: "emergency-41", speaker: "Caller", text: "Take care.", translation: "保重。", note: "道别。" },
    { id: "emergency-42", speaker: "Operator", text: "Take care.", translation: "保重。", note: "回应。" },
    { id: "emergency-43", speaker: "Caller", text: "Alright.", translation: "好的。", note: "确认。" },
    { id: "emergency-44", speaker: "Operator", text: "Alright.", translation: "好的。", note: "确认。" },
    { id: "emergency-45", speaker: "Caller", text: "Thanks.", translation: "谢谢。", note: "道谢。" },
    { id: "emergency-46", speaker: "Operator", text: "Anytime.", translation: "随时效劳。", note: "客气。" },
    { id: "emergency-47", speaker: "Caller", text: "Talk soon.", translation: "回头聊。", note: "告别。" },
    { id: "emergency-48", speaker: "Operator", text: "Talk soon.", translation: "回头聊。", note: "回应。" },
    { id: "emergency-49", speaker: "Caller", text: "Bye-bye.", translation: "拜拜。", note: "道别。" },
    { id: "emergency-50", speaker: "Operator", text: "Bye-bye.", translation: "拜拜。", note: "回应。" },
    { id: "emergency-51", speaker: "Caller", text: "Cheers!", translation: "干杯！", note: "致意。" },
    { id: "emergency-52", speaker: "Operator", text: "Cheers!", translation: "干杯！", note: "回礼。" },
    { id: "emergency-53", speaker: "Caller", text: "By the way, I wanted to ask you about the ambulance.", translation: "顺便问，我想问你关于救护车的事。", note: "询问话题" },
    { id: "emergency-54", speaker: "Operator", text: "I have been thinking about the hospital lately.", translation: "我最近一直在考虑医院。", note: "表达想法" },
    { id: "emergency-55", speaker: "Caller", text: "Do you have any thoughts on the treatment?", translation: "你对治疗有什么看法？", note: "征求意见" },
    { id: "emergency-56", speaker: "Operator", text: "By the way, I wanted to ask you about the police.", translation: "顺便问，我想问你关于警察的事。", note: "询问话题" },
    { id: "emergency-57", speaker: "Caller", text: "I have been thinking about the report lately.", translation: "我最近一直在考虑报告。", note: "表达想法" },
    { id: "emergency-58", speaker: "Operator", text: "Do you have any thoughts on the investigation?", translation: "你对调查有什么看法？", note: "征求意见" },
    { id: "emergency-59", speaker: "Caller", text: "By the way, I wanted to ask you about the witnesses.", translation: "顺便问，我想问你关于目击者的事。", note: "询问话题" },
    { id: "emergency-60", speaker: "Operator", text: "I have been thinking about the evidence lately.", translation: "我最近一直在考虑证据。", note: "表达想法" },
    { id: "emergency-61", speaker: "Caller", text: "Do you have any thoughts on the documentation?", translation: "你对文件有什么看法？", note: "征求意见" },
    { id: "emergency-62", speaker: "Operator", text: "By the way, I wanted to ask you about the follow-up.", translation: "顺便问，我想问你关于后续的事。", note: "询问话题" },
    { id: "emergency-63", speaker: "Caller", text: "I have been thinking about the recovery lately.", translation: "我最近一直在考虑恢复。", note: "表达想法" },
    { id: "emergency-64", speaker: "Operator", text: "Do you have any thoughts on the support?", translation: "你对支持有什么看法？", note: "征求意见" },
    { id: "emergency-65", speaker: "Caller", text: "By the way, I wanted to ask you about the insurance.", translation: "顺便问，我想问你关于保险的事。", note: "询问话题" },
    { id: "emergency-66", speaker: "Operator", text: "I have been thinking about the claim lately.", translation: "我最近一直在考虑索赔。", note: "表达想法" },
    { id: "emergency-67", speaker: "Caller", text: "Do you have any thoughts on the process?", translation: "你对流程有什么看法？", note: "征求意见" },
    { id: "emergency-68", speaker: "Operator", text: "By the way, I wanted to ask you about the paperwork.", translation: "顺便问，我想问你关于文件的事。", note: "询问话题" },
    { id: "emergency-69", speaker: "Caller", text: "I have been thinking about the forms lately.", translation: "我最近一直在考虑表格。", note: "表达想法" },
    { id: "emergency-70", speaker: "Operator", text: "Do you have any thoughts on the submission?", translation: "你对提交有什么看法？", note: "征求意见" },
    { id: "emergency-71", speaker: "Caller", text: "By the way, I wanted to ask you about the approval.", translation: "顺便问，我想问你关于批准的事。", note: "询问话题" },
    { id: "emergency-72", speaker: "Operator", text: "I have been thinking about the decision lately.", translation: "我最近一直在考虑决定。", note: "表达想法" },
    { id: "emergency-73", speaker: "Caller", text: "Do you have any thoughts on the outcome?", translation: "你对结果有什么看法？", note: "征求意见" },
    { id: "emergency-74", speaker: "Operator", text: "By the way, I wanted to ask you about the resolution.", translation: "顺便问，我想问你关于解决的事。", note: "询问话题" },
    { id: "emergency-75", speaker: "Caller", text: "I have been thinking about the closure lately.", translation: "我最近一直在考虑结案。", note: "表达想法" },
    { id: "emergency-76", speaker: "Operator", text: "Do you have any thoughts on the final report?", translation: "你对最终报告有什么看法？", note: "征求意见" },
    { id: "emergency-77", speaker: "Caller", text: "By the way, I wanted to ask you about the review.", translation: "顺便问，我想问你关于审核的事。", note: "询问话题" },
    { id: "emergency-78", speaker: "Operator", text: "I have been thinking about the assessment lately.", translation: "我最近一直在考虑评估。", note: "表达想法" },
    { id: "emergency-79", speaker: "Caller", text: "Do you have any thoughts on the evaluation?", translation: "你对评估有什么看法？", note: "征求意见" },
    { id: "emergency-80", speaker: "Operator", text: "By the way, I wanted to ask you about the feedback.", translation: "顺便问，我想听你关于反馈的事。", note: "询问话题" },
    { id: "emergency-81", speaker: "Caller", text: "I have been thinking about the improvement lately.", translation: "我最近一直在考虑改进。", note: "表达想法" },
    { id: "emergency-82", speaker: "Operator", text: "Do you have any thoughts on the prevention?", translation: "你对预防有什么看法？", note: "征求意见" },
    { id: "emergency-83", speaker: "Caller", text: "By the way, I wanted to ask you about the safety.", translation: "顺便问，我想问你关于安全的事。", note: "询问话题" },
    { id: "emergency-84", speaker: "Operator", text: "I have been thinking about the measures lately.", translation: "我最近一直在考虑措施。", note: "表达想法" },
    { id: "emergency-85", speaker: "Caller", text: "Do you have any thoughts on the protocol?", translation: "你对协议有什么看法？", note: "征求意见" },
    { id: "emergency-86", speaker: "Operator", text: "By the way, I wanted to ask you about the procedure.", translation: "顺便问，我想问你关于流程的事。", note: "询问话题" },
    { id: "emergency-87", speaker: "Caller", text: "I have been thinking about the steps lately.", translation: "我最近一直在考虑步骤。", note: "表达想法" },
    { id: "emergency-88", speaker: "Operator", text: "Do you have any thoughts on the action?", translation: "你对行动有什么看法？", note: "征求意见" },
    { id: "emergency-89", speaker: "Caller", text: "By the way, I wanted to ask you about the response.", translation: "顺便问，我想问你关于响应的事。", note: "询问话题" },
    { id: "emergency-90", speaker: "Operator", text: "I have been thinking about the reaction lately.", translation: "我最近一直在考虑反应。", note: "表达想法" },
    { id: "emergency-91", speaker: "Caller", text: "Do you have any thoughts on the result?", translation: "你对结果有什么看法？", note: "征求意见" },
    { id: "emergency-92", speaker: "Operator", text: "By the way, I wanted to ask you about the outcome.", translation: "顺便问，我想问你关于结果的事。", note: "询问话题" },
    { id: "emergency-93", speaker: "Caller", text: "I have been thinking about the impact lately.", translation: "我最近一直在考虑影响。", note: "表达想法" },
    { id: "emergency-94", speaker: "Operator", text: "Do you have any thoughts on the consequence?", translation: "你对后果有什么看法？", note: "征求意见" },
    { id: "emergency-95", speaker: "Caller", text: "By the way, I wanted to ask you about the lesson.", translation: "顺便问，我想听你关于教训的事。", note: "询问话题" },
    { id: "emergency-96", speaker: "Operator", text: "I have been thinking about the experience lately.", translation: "我最近一直在考虑经验。", note: "表达想法" },
    { id: "emergency-97", speaker: "Caller", text: "Do you have any thoughts on the reflection?", translation: "你对反思有什么看法？", note: "征求意见" },
    { id: "emergency-98", speaker: "Operator", text: "By the way, I wanted to ask you about the summary.", translation: "顺便问，我想听你关于总结的事。", note: "询问话题" },
    { id: "emergency-99", speaker: "Caller", text: "I have been thinking about the review lately.", translation: "我最近一直在考虑回顾。", note: "表达想法" },
    { id: "emergency-100", speaker: "Operator", text: "Do you have any thoughts on the future?", translation: "你对未来有什么看法？", note: "征求意见" },
  ],"""

# Replace emergency scene
emergency_pattern = r'  emergency: \[\n(?:    \{ id: "emergency-1"[^\n]*\n(?:    [^\n]*\n)*?    \{ id: "emergency-40"[^\n]*\n)\s*\],'
content = re.sub(emergency_pattern, EMERGENCY_SCENE, content, 1, re.DOTALL)

print("Emergency scene replaced successfully!")

with open("lib/data.ts", "w", encoding="utf-8") as f:
    f.write(content)

print("All scenes will be replaced in subsequent steps.")