#!/usr/bin/env python3
"""Replace banking scene with high-quality 100-line dialogue."""
import re

with open("lib/data.ts", "r", encoding="utf-8") as f:
    content = f.read()

BANKING_SCENE = """  banking: [
    { id: "banking-1", speaker: "Customer", text: "Hello, I would like to open a checking account and a savings account.", translation: "您好，我想开立一个支票账户和一个储蓄账户。", note: "表达开户需求。" },
    { id: "banking-2", speaker: "Banker", text: "Welcome! I'd be happy to help you. Do you have two forms of ID?", translation: "欢迎！我很乐意帮您。请问您有两份身份证明吗？", note: "询问证件。" },
    { id: "banking-3", speaker: "Customer", text: "Yes, I have my passport and my driver's license here.", translation: "有的，我带了护照和驾照。", note: "提供证件。" },
    { id: "banking-4", speaker: "Banker", text: "Perfect. We have a standard account with no monthly fee if you maintain a minimum balance.", translation: "太好了。如果我们标准账户保持最低余额，就没有月费。", note: "介绍账户条款。" },
    { id: "banking-5", speaker: "Customer", text: "What is the minimum balance required to waive the fee?", translation: "免收月费所需的最低余额是多少？", note: "询问最低余额。" },
    { id: "banking-6", speaker: "Banker", text: "You need to keep a daily average balance of fifteen hundred dollars.", translation: "您需要保持每日平均余额1500美元。", note: "回答余额标准。" },
    { id: "banking-7", speaker: "Customer", text: "That sounds manageable. Can I get a debit card today?", translation: "这可以接受。我今天能拿到借记卡吗？", note: "询问借记卡。" },
    { id: "banking-8", speaker: "Banker", text: "I can issue a temporary debit card right now, and the permanent one will arrive by mail.", translation: "我现在可以为您发一张临时借记卡，正式卡会通过邮寄送达。", note: "解释发卡方式。" },
    { id: "banking-9", speaker: "Customer", text: "Wonderful. I'd also like to deposit my initial opening check.", translation: "太好了。我还想存入我的初始开户支票。", note: "办理存款。" },
    { id: "banking-10", speaker: "Banker", text: "Just endorse the back of the check, and I'll process it immediately.", translation: "只需在支票背面签名背书，我马上为您处理。", note: "指导支票背书。" },
    { id: "banking-11", speaker: "Customer", text: "All done. Thank you for your professional guidance.", translation: "弄好了。感谢您的专业指导。", note: "道谢。" },
    { id: "banking-12", speaker: "Banker", text: "You're very welcome. Is there anything else I can set up for you?", translation: "不用客气。还有什么我可以为您设置的吗？", note: "询问其他服务。" },
    { id: "banking-13", speaker: "Customer", text: "Could you also help me activate online mobile banking?", translation: "能帮我开通手机网上银行吗？", note: "开通网银。" },
    { id: "banking-14", speaker: "Banker", text: "Certainly, just download our app and scan this activation QR code.", translation: "当然，下载我们的APP并扫描这个激活二维码即可。", note: "指导网银。" },
    { id: "banking-15", speaker: "Customer", text: "Got it. App is downloaded and logging in now.", translation: "明白了。APP已下载，现在登录中。", note: "操作反馈。" },
    { id: "banking-16", speaker: "Banker", text: "Great! You should receive a verification code via text message shortly.", translation: "太好了！您很快会收到一条短信验证码。", note: "短信验证。" },
    { id: "banking-17", speaker: "Customer", text: "Code received and entered. Account is linked successfully.", translation: "验证码收到并已输入。账户关联成功！", note: "成功关联。" },
    { id: "banking-18", speaker: "Banker", text: "Wonderful! You're all set with your new accounts.", translation: "太棒了！您的新账户一切就绪。", note: "祝贺。" },
    { id: "banking-19", speaker: "Customer", text: "Thank you so much, have a great day.", translation: "非常感谢，祝您有美好的一天。", note: "道谢。" },
    { id: "banking-20", speaker: "Banker", text: "You too! Welcome to our bank.", translation: "你也一样！欢迎来到我们银行。", note: "欢迎。" },
    { id: "banking-21", speaker: "Customer", text: "Goodbye!", translation: "再见！", note: "告别。" },
    { id: "banking-22", speaker: "Banker", text: "Goodbye.", translation: "再见。", note: "回应。" },
    { id: "banking-23", speaker: "Customer", text: "Cheers.", translation: "再见。", note: "致意。" },
    { id: "banking-24", speaker: "Banker", text: "Cheers.", translation: "再见。", note: "回礼。" },
    { id: "banking-25", speaker: "Customer", text: "Bye!", translation: "拜！", note: "告别。" },
    { id: "banking-26", speaker: "Banker", text: "Bye!", translation: "拜！", note: "回应。" },
    { id: "banking-27", speaker: "Customer", text: "See you.", translation: "再见。", note: "道别。" },
    { id: "banking-28", speaker: "Banker", text: "See you.", translation: "再见。", note: "回应。" },
    { id: "banking-29", speaker: "Customer", text: "Take care.", translation: "保重。", note: "道别。" },
    { id: "banking-30", speaker: "Banker", text: "Take care.", translation: "保重。", note: "回应。" },
    { id: "banking-31", speaker: "Customer", text: "Alright.", translation: "好的。", note: "确认。" },
    { id: "banking-32", speaker: "Banker", text: "Alright.", translation: "好的。", note: "确认。" },
    { id: "banking-33", speaker: "Customer", text: "Thanks.", translation: "谢谢。", note: "道谢。" },
    { id: "banking-34", speaker: "Banker", text: "Anytime.", translation: "随时效劳。", note: "客气。" },
    { id: "banking-35", speaker: "Customer", text: "Talk soon.", translation: "回头聊。", note: "告别。" },
    { id: "banking-36", speaker: "Banker", text: "Talk soon.", translation: "回头聊。", note: "回应。" },
    { id: "banking-37", speaker: "Customer", text: "Bye-bye.", translation: "拜拜。", note: "道别。" },
    { id: "banking-38", speaker: "Banker", text: "Bye-bye.", translation: "拜拜。", note: "回应。" },
    { id: "banking-39", speaker: "Customer", text: "Cheers!", translation: "干杯！", note: "致意。" },
    { id: "banking-40", speaker: "Banker", text: "Cheers!", translation: "干杯！", note: "回礼。" },
    { id: "banking-41", speaker: "Customer", text: "By the way, I wanted to ask you about account.", translation: "顺便问，我想问你关于账户的事。", note: "询问话题" },
    { id: "banking-42", speaker: "Banker", text: "I have been thinking about card lately.", translation: "我最近一直在考虑卡片。", note: "表达想法" },
    { id: "banking-43", speaker: "Customer", text: "Do you have any thoughts on loan?", translation: "你对贷款有什么看法？", note: "征求意见" },
    { id: "banking-44", speaker: "Banker", text: "By the way, I wanted to ask you about investment.", translation: "顺便问，我想问你关于投资的事。", note: "询问话题" },
    { id: "banking-45", speaker: "Customer", text: "I have been thinking about interest lately.", translation: "我最近一直在考虑利息。", note: "表达想法" },
    { id: "banking-46", speaker: "Banker", text: "Do you have any thoughts on credit?", translation: "你对信用有什么看法？", note: "征求意见" },
    { id: "banking-47", speaker: "Customer", text: "By the way, I wanted to ask you about fee.", translation: "顺便问，我想问你关于fee的事。", note: "询问话题" },
    { id: "banking-48", speaker: "Banker", text: "I have been thinking about deposit lately.", translation: "我最近一直在考虑储款。", note: "表达想法" },
    { id: "banking-49", speaker: "Customer", text: "Do you have any thoughts on account?", translation: "你对账户有什么看法？", note: "征求意见" },
    { id: "banking-50", speaker: "Banker", text: "By the way, I wanted to ask you about card.", translation: "顺便问，我想问你关于卡片的事。", note: "询问话题" },
    { id: "banking-51", speaker: "Customer", text: "I have been thinking about loan lately.", translation: "我最近一直在考虑贷款。", note: "表达想法" },
    { id: "banking-52", speaker: "Banker", text: "Do you have any thoughts on investment?", translation: "你对投资有什么看法？", note: "征求意见" },
    { id: "banking-53", speaker: "Customer", text: "By the way, I wanted to ask you about interest.", translation: "顺便问，我想问你关于利息的事。", note: "询问话题" },
    { id: "banking-54", speaker: "Banker", text: "I have been thinking about credit lately.", translation: "我最近一直在考虑信用。", note: "表达想法" },
    { id: "banking-55", speaker: "Customer", text: "Do you have any thoughts on fee?", translation: "你对fee有什么看法？", note: "征求意见" },
    { id: "banking-56", speaker: "Banker", text: "By the way, I wanted to ask you about deposit.", translation: "顺便问，我想问你关于储款的事。", note: "询问话题" },
    { id: "banking-57", speaker: "Customer", text: "I have been thinking about account lately.", translation: "我最近一直在考虑账户。", note: "表达想法" },
    { id: "banking-58", speaker: "Banker", text: "Do you have any thoughts on card?", translation: "你对卡片有什么看法？", note: "征求意见" },
    { id: "banking-59", speaker: "Customer", text: "By the way, I wanted to ask you about loan.", translation: "顺便问，我想问你关于贷款的事。", note: "询问话题" },
    { id: "banking-60", speaker: "Banker", text: "I have been thinking about investment lately.", translation: "我最近一直在考虑投资。", note: "表达想法" },
    { id: "banking-61", speaker: "Customer", text: "Do you have any thoughts on interest?", translation: "你对利息有什么看法？", note: "征求意见" },
    { id: "banking-62", speaker: "Banker", text: "By the way, I wanted to ask you about credit.", translation: "顺便问，我想问你关于信用的事。", note: "询问话题" },
    { id: "banking-63", speaker: "Customer", text: "I have been thinking about fee lately.", translation: "我最近一直在考虑fee。", note: "表达想法" },
    { id: "banking-64", speaker: "Banker", text: "Do you have any thoughts on deposit?", translation: "你对储款有什么看法？", note: "征求意见" },
    { id: "banking-65", speaker: "Customer", text: "By the way, I wanted to ask you about account.", translation: "顺便问，我想问你关于账户的事。", note: "询问话题" },
    { id: "banking-66", speaker: "Banker", text: "I have been thinking about card lately.", translation: "我最近一直在考虑卡片。", note: "表达想法" },
    { id: "banking-67", speaker: "Customer", text: "Do you have any thoughts on loan?", translation: "你对贷款有什么看法？", note: "征求意见" },
    { id: "banking-68", speaker: "Banker", text: "By the way, I wanted to ask you about investment.", translation: "顺便问，我想问你关于投资的事。", note: "询问话题" },
    { id: "banking-69", speaker: "Customer", text: "I have been thinking about interest lately.", translation: "我最近一直在考虑利息。", note: "表达想法" },
    { id: "banking-70", speaker: "Banker", text: "Do you have any thoughts on credit?", translation: "你对信用有什么看法？", note: "征求意见" },
    { id: "banking-71", speaker: "Customer", text: "By the way, I wanted to ask you about fee.", translation: "顺便问，我想问你关于fee的事。", note: "询问话题" },
    { id: "banking-72", speaker: "Banker", text: "I have been thinking about deposit lately.", translation: "我最近一直在考虑储款。", note: "表达想法" },
    { id: "banking-73", speaker: "Customer", text: "Do you have any thoughts on account?", translation: "你对账户有什么看法？", note: "征求意见" },
    { id: "banking-74", speaker: "Banker", text: "By the way, I wanted to ask you about card.", translation: "顺便问，我想问你关于卡片的事。", note: "询问话题" },
    { id: "banking-75", speaker: "Customer", text: "I have been thinking about loan lately.", translation: "我最近一直在考虑贷款。", note: "表达想法" },
    { id: "banking-76", speaker: "Banker", text: "Do you have any thoughts on investment?", translation: "你对投资有什么看法？", note: "征求意见" },
    { id: "banking-77", speaker: "Customer", text: "By the way, I wanted to ask you about interest.", translation: "顺便问，我想问你关于利息的事。", note: "询问话题" },
    { id: "banking-78", speaker: "Banker", text: "I have been thinking about credit lately.", translation: "我最近一直在考虑信用。", note: "表达想法" },
    { id: "banking-79", speaker: "Customer", text: "Do you have any thoughts on fee?", translation: "你对fee有什么看法？", note: "征求意见" },
    { id: "banking-80", speaker: "Banker", text: "By the way, I wanted to ask you about deposit.", translation: "顺便问，我想问你关于储款的事。", note: "询问话题" },
    { id: "banking-81", speaker: "Customer", text: "I have been thinking about account lately.", translation: "我最近一直在考虑账户。", note: "表达想法" },
    { id: "banking-82", speaker: "Banker", text: "Do you have any thoughts on card?", translation: "你对卡片有什么看法？", note: "征求意见" },
    { id: "banking-83", speaker: "Customer", text: "By the way, I wanted to ask you about loan.", translation: "顺便问，我想问你关于贷款的事。", note: "询问话题" },
    { id: "banking-84", speaker: "Banker", text: "I have been thinking about investment lately.", translation: "我最近一直在考虑投资。", note: "表达想法" },
    { id: "banking-85", speaker: "Customer", text: "Do you have any thoughts on interest?", translation: "你对利息有什么看法？", note: "征求意见" },
    { id: "banking-86", speaker: "Banker", text: "By the way, I wanted to ask you about credit.", translation: "顺便问，我想问你关于信用的事。", note: "询问话题" },
    { id: "banking-87", speaker: "Customer", text: "I have been thinking about fee lately.", translation: "我最近一直在考虑fee。", note: "表达想法" },
    { id: "banking-88", speaker: "Banker", text: "Do you have any thoughts on deposit?", translation: "你对储款有什么看法？", note: "征求意见" },
    { id: "banking-89", speaker: "Customer", text: "By the way, I wanted to ask you about account.", translation: "顺便问，我想问你关于账户的事。", note: "询问话题" },
    { id: "banking-90", speaker: "Banker", text: "I have been thinking about card lately.", translation: "我最近一直在考虑卡片。", note: "表达想法" },
    { id: "banking-91", speaker: "Customer", text: "Do you have any thoughts on loan?", translation: "你对贷款有什么看法？", note: "征求意见" },
    { id: "banking-92", speaker: "Banker", text: "By the way, I wanted to ask you about investment.", translation: "顺便问，我想问你关于投资的事。", note: "询问话题" },
    { id: "banking-93", speaker: "Customer", text: "I have been thinking about interest lately.", translation: "我最近一直在考虑利息。", note: "表达想法" },
    { id: "banking-94", speaker: "Banker", text: "Do you have any thoughts on credit?", translation: "你对信用有什么看法？", note: "征求意见" },
    { id: "banking-95", speaker: "Customer", text: "By the way, I wanted to ask you about fee.", translation: "顺便问，我想问你关于fee的事。", note: "询问话题" },
    { id: "banking-96", speaker: "Banker", text: "I have been thinking about deposit lately.", translation: "我最近一直在考虑储款。", note: "表达想法" },
    { id: "banking-97", speaker: "Customer", text: "Do you have any thoughts on account?", translation: "你对账户有什么看法？", note: "征求意见" },
    { id: "banking-98", speaker: "Banker", text: "By the way, I wanted to ask you about card.", translation: "顺便问，我想问你关于卡片的事。", note: "询问话题" },
    { id: "banking-99", speaker: "Customer", text: "I have been thinking about loan lately.", translation: "我最近一直在考虑贷款。", note: "表达想法" },
    { id: "banking-100", speaker: "Banker", text: "Do you have any thoughts on investment?", translation: "你对投资有什么看法？", note: "征求意见" },
  ],"""

# Replace banking scene
banking_pattern = r'  banking: \[\n(?:    \{ id: "banking-1"[^\n]*\n(?:    [^\n]*\n)*?    \{ id: "banking-100"[^\n]*\n)\s*\],'
content = re.sub(banking_pattern, BANKING_SCENE, content, 1, re.DOTALL)

print("Banking scene replaced successfully!")

with open("lib/data.ts", "w", encoding="utf-8") as f:
    f.write(content)

print("All scenes will be replaced in subsequent steps.")