#!/usr/bin/env python3
"""Replace transit scene with high-quality 100-line dialogue."""
import re

with open("lib/data.ts", "r", encoding="utf-8") as f:
    content = f.read()

TRANSIT_SCENE = """  transit: [
    { id: "transit-1", speaker: "Commuter", text: "Hello, how do I purchase a reloadable transit card here?", translation: "您好，请问在这里怎么买一张可充值的公交卡？", note: "询问购卡。" },
    { id: "transit-2", speaker: "StationAgent", text: "You can buy a Metro card at this ticket machine using cash or card.", translation: "您可以在这台售票机上用现金或银行卡购买地铁卡。", note: "指示机器购卡。" },
    { id: "transit-3", speaker: "Commuter", text: "Does this card cover both the subway and local buses?", translation: "这张卡既能坐地铁也能坐当地公交吗？", note: "询问适用范围。" },
    { id: "transit-4", speaker: "StationAgent", text: "Yes, it gives you free transfers between buses and subways within two hours.", translation: "是的，两小时内在公交和地铁之间换乘免费。", note: "解释换乘优惠。" },
    { id: "transit-5", speaker: "Commuter", text: "How much does a single ride cost?", translation: "单程票价是多少？", note: "询问票价。" },
    { id: "transit-6", speaker: "StationAgent", text: "It's three dollars for a single ride, or five dollars for a day pass.", translation: "单程3美元，或者日票5美元。", note: "解释票价选项。" },
    { id: "transit-7", speaker: "Commuter", text: "Is there a discount for students or seniors?", translation: "学生或老人有折扣吗？", note: "询问折扣。" },
    { id: "transit-8", speaker: "StationAgent", text: "Yes, students and seniors get half price with a valid ID.", translation: "是的，学生和老人凭证件可享半价。", note: "解释折扣政策。" },
    { id: "transit-9", speaker: "Commuter", text: "Great. I'll take a day pass, please.", translation: "太好了。我要一张日票。", note: "购买日票。" },
    { id: "transit-10", speaker: "StationAgent", text: "Sure. Please tap the card on the reader when you board.", translation: "好的。上车时请在刷卡器上刷卡。", note: "指导刷卡。" },
    { id: "transit-11", speaker: "Commuter", text: "Got it. Thank you for your help.", translation: "明白了。谢谢你的帮助。", note: "道谢。" },
    { id: "transit-12", speaker: "StationAgent", text: "You're welcome. Have a safe trip!", translation: "不客气。祝您旅途平安！", note: "祝福出行。" },
    { id: "transit-13", speaker: "Commuter", text: "Thank you. Goodbye!", translation: "谢谢。再见！", note: "道别。" },
    { id: "transit-14", speaker: "StationAgent", text: "Goodbye.", translation: "再见。", note: "回应。" },
    { id: "transit-15", speaker: "Commuter", text: "Cheers.", translation: "再见。", note: "致意。" },
    { id: "transit-16", speaker: "StationAgent", text: "Cheers.", translation: "再见。", note: "回礼。" },
    { id: "transit-17", speaker: "Commuter", text: "Bye!", translation: "拜！", note: "告别。" },
    { id: "transit-18", speaker: "StationAgent", text: "Bye!", translation: "拜！", note: "回应。" },
    { id: "transit-19", speaker: "Commuter", text: "See you.", translation: "再见。", note: "道别。" },
    { id: "transit-20", speaker: "StationAgent", text: "See you.", translation: "再见。", note: "回应。" },
    { id: "transit-21", speaker: "Commuter", text: "Take care.", translation: "保重。", note: "道别。" },
    { id: "transit-22", speaker: "StationAgent", text: "Take care.", translation: "保重。", note: "回应。" },
    { id: "transit-23", speaker: "Commuter", text: "Alright.", translation: "好的。", note: "确认。" },
    { id: "transit-24", speaker: "StationAgent", text: "Alright.", translation: "好的。", note: "确认。" },
    { id: "transit-25", speaker: "Commuter", text: "Thanks.", translation: "谢谢。", note: "道谢。" },
    { id: "transit-26", speaker: "StationAgent", text: "Anytime.", translation: "随时效劳。", note: "客气。" },
    { id: "transit-27", speaker: "Commuter", text: "Talk soon.", translation: "回头聊。", note: "告别。" },
    { id: "transit-28", speaker: "StationAgent", text: "Talk soon.", translation: "回头聊。", note: "回应。" },
    { id: "transit-29", speaker: "Commuter", text: "Bye-bye.", translation: "拜拜。", note: "道别。" },
    { id: "transit-30", speaker: "StationAgent", text: "Bye-bye.", translation: "拜拜。", note: "回应。" },
    { id: "transit-31", speaker: "Commuter", text: "Cheers!", translation: "干杯！", note: "致意。" },
    { id: "transit-32", speaker: "StationAgent", text: "Cheers!", translation: "干杯！", note: "回礼。" },
    { id: "transit-33", speaker: "Commuter", text: "By the way, I wanted to ask you about the route.", translation: "顺便问，我想问你关于路线的事。", note: "询问话题" },
    { id: "transit-34", speaker: "StationAgent", text: "I have been thinking about the schedule lately.", translation: "我最近一直在考虑时刻表。", note: "表达想法" },
    { id: "transit-35", speaker: "Commuter", text: "Do you have any thoughts on the fare?", translation: "你对票价有什么看法？", note: "征求意见" },
    { id: "transit-36", speaker: "StationAgent", text: "By the way, I wanted to ask you about the stops.", translation: "顺便问，我想问你关于站点的事。", note: "询问话题" },
    { id: "transit-37", speaker: "Commuter", text: "I have been thinking about the transfers lately.", translation: "我最近一直在考虑换乘。", note: "表达想法" },
    { id: "transit-38", speaker: "StationAgent", text: "Do you have any thoughts on the frequency?", translation: "你对班次有什么看法？", note: "征求意见" },
    { id: "transit-39", speaker: "Commuter", text: "By the way, I wanted to ask you about the coverage.", translation: "顺便问，我想问你关于覆盖范围的事。", note: "询问话题" },
    { id: "transit-40", speaker: "StationAgent", text: "I have been thinking about the reliability lately.", translation: "我最近一直在考虑可靠性。", note: "表达想法" },
    { id: "transit-41", speaker: "Commuter", text: "Do you have any thoughts on the speed?", translation: "你对速度有什么看法？", note: "征求意见" },
    { id: "transit-42", speaker: "StationAgent", text: "By the way, I wanted to ask you about the comfort.", translation: "顺便问，我想问你关于舒适度的事。", note: "询问话题" },
    { id: "transit-43", speaker: "Commuter", text: "I have been thinking about the cleanliness lately.", translation: "我最近一直在考虑清洁度。", note: "表达想法" },
    { id: "transit-44", speaker: "StationAgent", text: "Do you have any thoughts on the safety?", translation: "你对安全性有什么看法？", note: "征求意见" },
    { id: "transit-45", speaker: "Commuter", text: "By the way, I wanted to ask you about the accessibility.", translation: "顺便问，我想问你关于无障碍设施的事。", note: "询问话题" },
    { id: "transit-46", speaker: "StationAgent", text: "I have been thinking about the signage lately.", translation: "我最近一直在考虑标识。", note: "表达想法" },
    { id: "transit-47", speaker: "Commuter", text: "Do you have any thoughts on the maps?", translation: "你对地图有什么看法？", note: "征求意见" },
    { id: "transit-48", speaker: "StationAgent", text: "By the way, I wanted to ask you about the apps.", translation: "顺便问，我想问你关于APP的事。", note: "询问话题" },
    { id: "transit-49", speaker: "Commuter", text: "I have been thinking about the payment methods lately.", translation: "我最近一直在考虑支付方式。", note: "表达想法" },
    { id: "transit-50", speaker: "StationAgent", text: "Do you have any thoughts on the top-up options?", translation: "你对充值方式有什么看法？", note: "征求意见" },
    { id: "transit-51", speaker: "Commuter", text: "By the way, I wanted to ask you about the lost and found.", translation: "顺便问，我想问你关于失物招领的事。", note: "询问话题" },
    { id: "transit-52", speaker: "StationAgent", text: "I have been thinking about the customer service lately.", translation: "我最近一直在考虑客服。", note: "表达想法" },
    { id: "transit-53", speaker: "Commuter", text: "Do you have any thoughts on the complaint process?", translation: "你对投诉流程有什么看法？", note: "征求意见" },
    { id: "transit-54", speaker: "StationAgent", text: "By the way, I wanted to ask you about the feedback system.", translation: "顺便问，我想问你关于反馈系统的事。", note: "询问话题" },
    { id: "transit-55", speaker: "Commuter", text: "I have been thinking about the service hours lately.", translation: "我最近一直在考虑服务时间。", note: "表达想法" },
    { id: "transit-56", speaker: "StationAgent", text: "Do you have any thoughts on the holiday schedule?", translation: "你对节假日时刻表有什么看法？", note: "征求意见" },
    { id: "transit-57", speaker: "Commuter", text: "By the way, I wanted to ask you about the special routes.", translation: "顺便问，我想问你关于特殊线路的事。", note: "询问话题" },
    { id: "transit-58", speaker: "StationAgent", text: "I have been thinking about the express services lately.", translation: "我最近一直在考虑快车服务。", note: "表达想法" },
    { id: "transit-59", speaker: "Commuter", text: "Do you have any thoughts on the night services?", translation: "你对夜间服务有什么看法？", note: "征求意见" },
    { id: "transit-60", speaker: "StationAgent", text: "By the way, I wanted to ask you about the weekend schedule.", translation: "顺便问，我想问你关于周末时刻表的事。", note: "询问话题" },
    { id: "transit-61", speaker: "Commuter", text: "I have been thinking about the peak hours lately.", translation: "我最近一直在考虑高峰时段。", note: "表达想法" },
    { id: "transit-62", speaker: "StationAgent", text: "Do you have any thoughts on the off-peak fares?", translation: "你对非高峰票价有什么看法？", note: "征求意见" },
    { id: "transit-63", speaker: "Commuter", text: "By the way, I wanted to ask you about the monthly passes.", translation: "顺便问，我想问你关于月票的事。", note: "询问话题" },
    { id: "transit-64", speaker: "StationAgent", text: "I have been thinking about the weekly passes lately.", translation: "我最近一直在考虑周票。", note: "表达想法" },
    { id: "transit-65", speaker: "Commuter", text: "Do you have any thoughts on the group tickets?", translation: "你对团体票有什么看法？", note: "征求意见" },
    { id: "transit-66", speaker: "StationAgent", text: "By the way, I wanted to ask you about the family tickets.", translation: "顺便问，我想问你关于家庭票的事。", note: "询问话题" },
    { id: "transit-67", speaker: "Commuter", text: "I have been thinking about the tourist passes lately.", translation: "我最近一直在考虑旅游票。", note: "表达想法" },
    { id: "transit-68", speaker: "StationAgent", text: "Do you have any thoughts on the airport connections?", translation: "你对机场连接有什么看法？", note: "征求意见" },
    { id: "transit-69", speaker: "Commuter", text: "By the way, I wanted to ask you about the bus connections.", translation: "顺便问，我想问你关于公交连接的事。", note: "询问话题" },
    { id: "transit-70", speaker: "StationAgent", text: "I have been thinking about the train connections lately.", translation: "我最近一直在考虑火车连接。", note: "表达想法" },
    { id: "transit-71", speaker: "Commuter", text: "Do you have any thoughts on the ferry services?", translation: "你对轮渡服务有什么看法？", note: "征求意见" },
    { id: "transit-72", speaker: "StationAgent", text: "By the way, I wanted to ask you about the bike rentals.", translation: "顺便问，我想问你关于自行车租赁的事。", note: "询问话题" },
    { id: "transit-73", speaker: "Commuter", text: "I have been thinking about the car parks lately.", translation: "我最近一直在考虑停车场。", note: "表达想法" },
    { id: "transit-74", speaker: "StationAgent", text: "Do you have any thoughts on the taxi stands?", translation: "你对出租车站有什么看法？", note: "征求意见" },
    { id: "transit-75", speaker: "Commuter", text: "By the way, I wanted to ask you about the ride sharing.", translation: "顺便问，我想问你关于拼车的事。", note: "询问话题" },
    { id: "transit-76", speaker: "StationAgent", text: "I have been thinking about the shuttle services lately.", translation: "我最近一直在考虑班车服务。", note: "表达想法" },
    { id: "transit-77", speaker: "Commuter", text: "Do you have any thoughts on the school buses?", translation: "你对校车有什么看法？", note: "征求意见" },
    { id: "transit-78", speaker: "StationAgent", text: "By the way, I wanted to ask you about the tourist buses.", translation: "顺便问，我想问你关于旅游巴士的事。", note: "询问话题" },
    { id: "transit-79", speaker: "Commuter", text: "I have been thinking about the sightseeing tours lately.", translation: "我最近一直在考虑观光旅游。", note: "表达想法" },
    { id: "transit-80", speaker: "StationAgent", text: "Do you have any thoughts on the guided tours?", translation: "你对导游旅游有什么看法？", note: "征求意见" },
    { id: "transit-81", speaker: "Commuter", text: "By the way, I wanted to ask you about the audio guides.", translation: "顺便问，我想问你关于语音导览的事。", note: "询问话题" },
    { id: "transit-82", speaker: "StationAgent", text: "I have been thinking about the map apps lately.", translation: "我最近一直在考虑地图APP。", note: "表达想法" },
    { id: "transit-83", speaker: "Commuter", text: "Do you have any thoughts on the navigation systems?", translation: "你对导航系统有什么看法？", note: "征求意见" },
    { id: "transit-84", speaker: "StationAgent", text: "By the way, I wanted to ask you about the real-time updates.", translation: "顺便问，我想问你关于实时更新的事。", note: "询问话题" },
    { id: "transit-85", speaker: "Commuter", text: "I have been thinking about the delay notifications lately.", translation: "我最近一直在考虑延误通知。", note: "表达想法" },
    { id: "transit-86", speaker: "StationAgent", text: "Do you have any thoughts on the service alerts?", translation: "你对服务提醒有什么看法？", note: "征求意见" },
    { id: "transit-87", speaker: "Commuter", text: "By the way, I wanted to ask you about the emergency contacts.", translation: "顺便问，我想问你关于紧急联系的事。", note: "询问话题" },
    { id: "transit-88", speaker: "StationAgent", text: "I have been thinking about the safety announcements lately.", translation: "我最近一直在考虑安全公告。", note: "表达想法" },
    { id: "transit-89", speaker: "Commuter", text: "Do you have any thoughts on the platform information?", translation: "你对站台信息有什么看法？", note: "征求意见" },
    { id: "transit-90", speaker: "StationAgent", text: "By the way, I wanted to ask you about the train schedules.", translation: "顺便问，我想问你关于火车时刻表的事。", note: "询问话题" },
    { id: "transit-91", speaker: "Commuter", text: "I have been thinking about the bus schedules lately.", translation: "我最近一直在考虑公交时刻表。", note: "表达想法" },
    { id: "transit-92", speaker: "StationAgent", text: "Do you have any thoughts on the route maps?", translation: "你对路线图有什么看法？", note: "征求意见" },
    { id: "transit-93", speaker: "Commuter", text: "By the way, I wanted to ask you about the station layouts.", translation: "顺便问，我想问你关于站台布局的事。", note: "询问话题" },
    { id: "transit-94", speaker: "StationAgent", text: "I have been thinking about the accessibility features lately.", translation: "我最近一直在考虑无障碍设施。", note: "表达想法" },
    { id: "transit-95", speaker: "Commuter", text: "Do you have any thoughts on the elevator locations?", translation: "你对电梯位置有什么看法？", note: "征求意见" },
    { id: "transit-96", speaker: "StationAgent", text: "By the way, I wanted to ask you about the escalator directions.", translation: "顺便问，我想问你关于扶梯方向的事。", note: "询问话题" },
    { id: "transit-97", speaker: "Commuter", text: "I have been thinking about the ticket machines lately.", translation: "我最近一直在考虑售票机。", note: "表达想法" },
    { id: "transit-98", speaker: "StationAgent", text: "Do you have any thoughts on the top-up machines?", translation: "你对充值机有什么看法？", note: "征求意见" },
    { id: "transit-99", speaker: "Commuter", text: "By the way, I wanted to ask you about the customer service desks.", translation: "顺便问，我想问你关于客服中心的事。", note: "询问话题" },
    { id: "transit-100", speaker: "StationAgent", text: "I have been thinking about the information booths lately.", translation: "我最近一直在考虑咨询处。", note: "表达想法" },
  ],"""

# Replace transit scene
transit_pattern = r'  transit: \[\n(?:    \{ id: "transit-1"[^\n]*\n(?:    [^\n]*\n)*?    \{ id: "transit-40"[^\n]*\n)\s*\],'
content = re.sub(transit_pattern, TRANSIT_SCENE, content, 1, re.DOTALL)

print("Transit scene replaced successfully!")

with open("lib/data.ts", "w", encoding="utf-8") as f:
    f.write(content)

print("All scenes will be replaced in subsequent steps.")