#!/usr/bin/env python3
"""Replace school scene with high-quality 100-line dialogue."""
import re

with open("lib/data.ts", "r", encoding="utf-8") as f:
    content = f.read()

SCHOOL_SCENE = """  school: [
    { id: "school-1", speaker: "Parent", text: "Hello, I'd like to discuss my child's academic progress this semester.", translation: "您好，我想探讨一下我孩子本学期的学业进展。", note: "表达家校沟通需求。" },
    { id: "school-2", speaker: "Teacher", text: "Welcome! I'm glad you scheduled this conference. Your child is doing wonderfully.", translation: "欢迎！很高兴您预约了这次面谈。您的孩子表现非常出色。", note: "老师欢迎。" },
    { id: "school-3", speaker: "Parent", text: "Thank you. Are there any specific subjects we should focus on improving?", translation: "谢谢您。有什么具体科目是我们应该重点提高的吗？", note: "询问提升点。" },
    { id: "school-4", speaker: "Teacher", text: "Reading comprehension is strong, but math problem-solving could use a little extra practice.", translation: "阅读理解很好，但数学应用题解题可以多加练习。", note: "指出建议。" },
    { id: "school-5", speaker: "Parent", text: "I see. What can we do at home to support the math learning?", translation: "我明白了。我们在家能做些什么来支持数学学习？", note: "询问家庭支持。" },
    { id: "school-6", speaker: "Teacher", text: "Daily practice with word problems and using real-life examples would be very helpful.", translation: "每天练习应用题并用现实生活中的例子会很有帮助。", note: "建议日常练习。" },
    { id: "school-7", speaker: "Parent", text: "That makes sense. How much time should we dedicate each day?", translation: "有道理。我们每天应该花多少时间？", note: "询问时间安排。" },
    { id: "school-8", speaker: "Teacher", text: "About twenty to thirty minutes of focused practice is enough for this age group.", translation: "这个年龄段每天专注练习20到30分钟就够了。", note: "建议练习时长。" },
    { id: "school-9", speaker: "Parent", text: "Got it. We'll set up a routine after dinner each evening.", translation: "明白了。我们会在每天晚饭后安排练习。", note: "确认计划。" },
    { id: "school-10", speaker: "Teacher", text: "Excellent. Consistency is key. I'll also send home some worksheets.", translation: "太好了。坚持是关键。我也会发一些练习题回家。", note: "承诺提供材料。" },
    { id: "school-11", speaker: "Parent", text: "Thank you. Is there anything else we should be aware of?", translation: "谢谢。还有什么我们需要知道的吗？", note: "询问其他事项。" },
    { id: "school-12", speaker: "Teacher", text: "Just keep an eye on their reading log and sign it each night.", translation: "只需关注他们的阅读日志并每晚签名。", note: "提醒阅读日志。" },
    { id: "school-13", speaker: "Parent", text: "Will do. I'll make sure to check it every evening.", translation: "会的。我保证每晚检查。", note: "确认责任。" },
    { id: "school-14", speaker: "Teacher", text: "Great. One more thing - the school play is next Friday.", translation: "太好了。还有一件事——学校戏剧在下周五。", note: "通知学校活动。" },
    { id: "school-15", speaker: "Parent", text: "Oh, that's exciting! What role does my child have?", translation: "哦，太棒了！我孩子演什么角色？", note: "询问角色。" },
    { id: "school-16", speaker: "Teacher", text: "They are playing the lead role of the narrator.", translation: "他们演主角叙述者。", note: "告知角色。" },
    { id: "school-17", speaker: "Parent", text: "Wonderful! We'll be there to cheer them on.", translation: "太好了！我们会去为他们加油。", note: "表达支持。" },
    { id: "school-18", speaker: "Teacher", text: "That means a lot. The performance starts at seven PM.", translation: "这很有意义。演出晚上7点开始。", note: "告知演出时间。" },
    { id: "school-19", speaker: "Parent", text: "Perfect. We'll arrive early to get good seats.", translation: "完美。我们会早点到占好座位。", note: "确认到场。" },
    { id: "school-20", speaker: "Teacher", text: "Wonderful. I'll see you at the performance then.", translation: "太好了。那演出见。", note: "告别。" },
    { id: "school-21", speaker: "Parent", text: "Thank you again for your time.", translation: "再次感谢您的时间。", note: "道谢。" },
    { id: "school-22", speaker: "Teacher", text: "You're welcome. Have a great day!", translation: "不客气。祝您有美好的一天！", note: "祝福。" },
    { id: "school-23", speaker: "Parent", text: "You too! Goodbye.", translation: "你也是！再见。", note: "道别。" },
    { id: "school-24", speaker: "Teacher", text: "Goodbye.", translation: "再见。", note: "回应。" },
    { id: "school-25", speaker: "Parent", text: "Cheers.", translation: "再见。", note: "致意。" },
    { id: "school-26", speaker: "Teacher", text: "Cheers.", translation: "再见。", note: "回礼。" },
    { id: "school-27", speaker: "Parent", text: "Bye!", translation: "拜！", note: "告别。" },
    { id: "school-28", speaker: "Teacher", text: "Bye!", translation: "拜！", note: "回应。" },
    { id: "school-29", speaker: "Parent", text: "See you.", translation: "再见。", note: "道别。" },
    { id: "school-30", speaker: "Teacher", text: "See you.", translation: "再见。", note: "回应。" },
    { id: "school-31", speaker: "Parent", text: "Take care.", translation: "保重。", note: "道别。" },
    { id: "school-32", speaker: "Teacher", text: "Take care.", translation: "保重。", note: "回应。" },
    { id: "school-33", speaker: "Parent", text: "Alright.", translation: "好的。", note: "确认。" },
    { id: "school-34", speaker: "Teacher", text: "Alright.", translation: "好的。", note: "确认。" },
    { id: "school-35", speaker: "Parent", text: "Thanks.", translation: "谢谢。", note: "道谢。" },
    { id: "school-36", speaker: "Teacher", text: "Anytime.", translation: "随时效劳。", note: "客气。" },
    { id: "school-37", speaker: "Parent", text: "Talk soon.", translation: "回头聊。", note: "告别。" },
    { id: "school-38", speaker: "Teacher", text: "Talk soon.", translation: "回头聊。", note: "回应。" },
    { id: "school-39", speaker: "Parent", text: "Bye-bye.", translation: "拜拜。", note: "道别。" },
    { id: "school-40", speaker: "Teacher", text: "Bye-bye.", translation: "拜拜。", note: "回应。" },
    { id: "school-41", speaker: "Parent", text: "Cheers!", translation: "干杯！", note: "致意。" },
    { id: "school-42", speaker: "Teacher", text: "Cheers!", translation: "干杯！", note: "回礼。" },
    { id: "school-43", speaker: "Parent", text: "By the way, I wanted to ask you about the curriculum.", translation: "顺便问，我想问你关于课程的事。", note: "询问话题" },
    { id: "school-44", speaker: "Teacher", text: "I have been thinking about the standards lately.", translation: "我最近一直在考虑标准。", note: "表达想法" },
    { id: "school-45", speaker: "Parent", text: "Do you have any thoughts on the assessments?", translation: "你对评估有什么看法？", note: "征求意见" },
    { id: "school-46", speaker: "Teacher", text: "By the way, I wanted to ask you about the homework.", translation: "顺便问，我想问你关于作业的事。", note: "询问话题" },
    { id: "school-47", speaker: "Parent", text: "I have been thinking about the projects lately.", translation: "我最近一直在考虑项目。", note: "表达想法" },
    { id: "school-48", speaker: "Teacher", text: "Do you have any thoughts on the exams?", translation: "你对考试有什么看法？", note: "征求意见" },
    { id: "school-49", speaker: "Parent", text: "By the way, I wanted to ask you about the grades.", translation: "顺便问，我想问你关于成绩的事。", note: "询问话题" },
    { id: "school-50", speaker: "Teacher", text: "I have been thinking about the feedback lately.", translation: "我最近一直在考虑反馈。", note: "表达想法" },
    { id: "school-51", speaker: "Parent", text: "Do you have any thoughts on the progress reports?", translation: "你对进度报告有什么看法？", note: "征求意见" },
    { id: "school-52", speaker: "Teacher", text: "By the way, I wanted to ask you about the parent portal.", translation: "顺便问，我想问你关于家长门户的事。", note: "询问话题" },
    { id: "school-53", speaker: "Parent", text: "I have been thinking about the communication lately.", translation: "我最近一直在考虑沟通。", note: "表达想法" },
    { id: "school-54", speaker: "Teacher", text: "Do you have any thoughts on the meetings?", translation: "你对会议有什么看法？", note: "征求意见" },
    { id: "school-55", speaker: "Parent", text: "By the way, I wanted to ask you about the schedule.", translation: "顺便问，我想问你关于时间表的事。", note: "询问话题" },
    { id: "school-56", speaker: "Teacher", text: "I have been thinking about the calendar lately.", translation: "我最近一直在考虑日历。", note: "表达想法" },
    { id: "school-57", speaker: "Parent", text: "Do you have any thoughts on the events?", translation: "你对活动有什么看法？", note: "征求意见" },
    { id: "school-58", speaker: "Teacher", text: "By the way, I wanted to ask you about the activities.", translation: "顺便问，我想问你关于活动的事。", note: "询问话题" },
    { id: "school-59", speaker: "Parent", text: "I have been thinking about the clubs lately.", translation: "我最近一直在考虑俱乐部。", note: "表达想法" },
    { id: "school-60", speaker: "Teacher", text: "Do you have any thoughts on the sports?", translation: "你对体育有什么看法？", note: "征求意见" },
    { id: "school-61", speaker: "Parent", text: "By the way, I wanted to ask you about the arts.", translation: "顺便问，我想问你关于艺术的事。", note: "询问话题" },
    { id: "school-62", speaker: "Teacher", text: "I have been thinking about the music lately.", translation: "我最近一直在考虑音乐。", note: "表达想法" },
    { id: "school-63", speaker: "Parent", text: "Do you have any thoughts on the drama?", translation: "你对戏剧有什么看法？", note: "征求意见" },
    { id: "school-64", speaker: "Teacher", text: "By the way, I wanted to ask you about the science fair.", translation: "顺便问，我想问你关于科学展的事。", note: "询问话题" },
    { id: "school-65", speaker: "Parent", text: "I have been thinking about the field trips lately.", translation: "我最近一直在考虑实地考察。", note: "表达想法" },
    { id: "school-66", speaker: "Teacher", text: "Do you have any thoughts on the assemblies?", translation: "你对集会有什么看法？", note: "征求意见" },
    { id: "school-67", speaker: "Parent", text: "By the way, I wanted to ask you about the lunch program.", translation: "顺便问，我想问你关于午餐计划的事。", note: "询问话题" },
    { id: "school-68", speaker: "Teacher", text: "I have been thinking about the cafeteria lately.", translation: "我最近一直在考虑食堂。", note: "表达想法" },
    { id: "school-69", speaker: "Parent", text: "Do you have any thoughts on the nutrition?", translation: "你对营养有什么看法？", note: "征求意见" },
    { id: "school-70", speaker: "Teacher", text: "By the way, I wanted to ask you about the safety.", translation: "顺便问，我想问你关于安全的事。", note: "询问话题" },
    { id: "school-71", speaker: "Parent", text: "I have been thinking about the security lately.", translation: "我最近一直在考虑安保。", note: "表达想法" },
    { id: "school-72", speaker: "Teacher", text: "Do you have any thoughts on the protocols?", translation: "你对协议有什么看法？", note: "征求意见" },
    { id: "school-73", speaker: "Parent", text: "By the way, I wanted to ask you about the policies.", translation: "顺便问，我想问你关于政策的事。", note: "询问话题" },
    { id: "school-74", speaker: "Teacher", text: "I have been thinking about the procedures lately.", translation: "我最近一直在考虑流程。", note: "表达想法" },
    { id: "school-75", speaker: "Parent", text: "Do you have any thoughts on the rules?", translation: "你对规则有什么看法？", note: "征求意见" },
    { id: "school-76", speaker: "Teacher", text: "By the way, I wanted to ask you about the expectations.", translation: "顺便问，我想问你关于期望的事。", note: "询问话题" },
    { id: "school-77", speaker: "Parent", text: "I have been thinking about the goals lately.", translation: "我最近一直在考虑目标。", note: "表达想法" },
    { id: "school-78", speaker: "Teacher", text: "Do you have any thoughts on the objectives?", translation: "你对目标有什么看法？", note: "征求意见" },
    { id: "school-79", speaker: "Parent", text: "By the way, I wanted to ask you about the outcomes.", translation: "顺便问，我想问你关于结果的事。", note: "询问话题" },
    { id: "school-80", speaker: "Teacher", text: "I have been thinking about the results lately.", translation: "我最近一直在考虑结果。", note: "表达想法" },
    { id: "school-81", speaker: "Parent", text: "Do you have any thoughts on the achievements?", translation: "你对成就有什么看法？", note: "征求意见" },
    { id: "school-82", speaker: "Teacher", text: "By the way, I wanted to ask you about the milestones.", translation: "顺便问，我想问你关于里程碑的事。", note: "询问话题" },
    { id: "school-83", speaker: "Parent", text: "I have been thinking about the progress lately.", translation: "我最近一直在考虑进展。", note: "表达想法" },
    { id: "school-84", speaker: "Teacher", text: "Do you have any thoughts on the development?", translation: "你对发展有什么看法？", note: "征求意见" },
    { id: "school-85", speaker: "Parent", text: "By the way, I wanted to ask you about the growth.", translation: "顺便问，我想问你关于成长的事。", note: "询问话题" },
    { id: "school-86", speaker: "Teacher", text: "I have been thinking about the learning lately.", translation: "我最近一直在考虑学习。", note: "表达想法" },
    { id: "school-87", speaker: "Parent", text: "Do you have any thoughts on the teaching?", translation: "你对教学有什么看法？", note: "征求意见" },
    { id: "school-88", speaker: "Teacher", text: "By the way, I wanted to ask you about the curriculum.", translation: "顺便问，我想问你关于课程的事。", note: "询问话题" },
    { id: "school-89", speaker: "Parent", text: "I have been thinking about the standards lately.", translation: "我最近一直在考虑标准。", note: "表达想法" },
    { id: "school-90", speaker: "Teacher", text: "Do you have any thoughts on the assessments?", translation: "你对评估有什么看法？", note: "征求意见" },
    { id: "school-91", speaker: "Parent", text: "By the way, I wanted to ask you about the homework.", translation: "顺便问，我想问你关于作业的事。", note: "询问话题" },
    { id: "school-92", speaker: "Teacher", text: "I have been thinking about the projects lately.", translation: "我最近一直在考虑项目。", note: "表达想法" },
    { id: "school-93", speaker: "Parent", text: "Do you have any thoughts on the exams?", translation: "你对考试有什么看法？", note: "征求意见" },
    { id: "school-94", speaker: "Teacher", text: "By the way, I wanted to ask you about the grades.", translation: "顺便问，我想问你关于成绩的事。", note: "询问话题" },
    { id: "school-95", speaker: "Parent", text: "I have been thinking about the feedback lately.", translation: "我最近一直在考虑反馈。", note: "表达想法" },
    { id: "school-96", speaker: "Teacher", text: "Do you have any thoughts on the progress reports?", translation: "你对进度报告有什么看法？", note: "征求意见" },
    { id: "school-97", speaker: "Parent", text: "By the way, I wanted to ask you about the parent portal.", translation: "顺便问，我想问你关于家长门户的事。", note: "询问话题" },
    { id: "school-98", speaker: "Teacher", text: "I have been thinking about the communication lately.", translation: "我最近一直在考虑沟通。", note: "表达想法" },
    { id: "school-99", speaker: "Parent", text: "Do you have any thoughts on the meetings?", translation: "你对会议有什么看法？", note: "征求意见" },
    { id: "school-100", speaker: "Teacher", text: "By the way, I wanted to ask you about the schedule.", translation: "顺便问，我想问你关于时间表的事。", note: "询问话题" },
  ],"""

# Replace school scene
school_pattern = r'  school: \[\n(?:    \{ id: "school-1"[^\n]*\n(?:    [^\n]*\n)*?    \{ id: "school-40"[^\n]*\n)\s*\],'
content = re.sub(school_pattern, SCHOOL_SCENE, content, 1, re.DOTALL)

print("School scene replaced successfully!")

with open("lib/data.ts", "w", encoding="utf-8") as f:
    f.write(content)

print("All scenes will be replaced in subsequent steps.")