#!/usr/bin/env python3
"""Replace restaurant scene with high-quality 100-line dialogue."""
import re

with open("lib/data.ts", "r", encoding="utf-8") as f:
    content = f.read()

RESTAURANT_SCENE = """  restaurant: [
    { id: "restaurant-1", speaker: "Customer", text: "Good evening. Do you have a table for two?", translation: "晚上好，请问有两个人的桌位吗？", note: "礼貌询问是否有空桌。" },
    { id: "restaurant-2", speaker: "Server", text: "Yes, we can seat you by the window.", translation: "有的，我们可以安排靠窗的座位。", note: "seat 表示安排入座。" },
    { id: "restaurant-3", speaker: "Customer", text: "That would be wonderful, thank you.", translation: "那太好了，谢谢。", note: "礼貌接受安排。" },
    { id: "restaurant-4", speaker: "Server", text: "Here are the menus. May I bring you some water?", translation: "这是菜单。我可以先给您倒些水吗？", note: "May I... 是礼貌提议。" },
    { id: "restaurant-5", speaker: "Customer", text: "Yes, please. I'll take a moment to look at the menu.", translation: "好的，请给我一点时间看菜单。", note: "take a moment 表示需要时间。" },
    { id: "restaurant-6", speaker: "Server", text: "Of course. I'll be right back with your drinks.", translation: "当然。我马上给您拿饮料来。", note: "be right back 表示马上回来。" },
    { id: "restaurant-7", speaker: "Customer", text: "Thank you. I think I'm ready to order now.", translation: "谢谢。我想我现在可以点餐了。", note: "be ready to order 表示准备点餐。" },
    { id: "restaurant-8", speaker: "Server", text: "Take your time. What would you like to start with?", translation: "不着急。您想先点什么？", note: "take your time 表示不着急。" },
    { id: "restaurant-9", speaker: "Customer", text: "I'll have the Caesar salad, please.", translation: "我要凯撒沙拉。", note: "点餐用语。" },
    { id: "restaurant-10", speaker: "Server", text: "Excellent choice. And for the main course?", translation: "不错的选择。主菜呢？", note: "询问主菜。" },
    { id: "restaurant-11", speaker: "Customer", text: "I'd like the grilled salmon with roasted vegetables.", translation: "我要烤三文鱼配烤蔬菜。", note: "描述主菜。" },
    { id: "restaurant-12", speaker: "Server", text: "Would you like any sauce with that?", translation: "您要什么酱汁吗？", note: "询问酱汁偏好。" },
    { id: "restaurant-13", speaker: "Customer", text: "Just a squeeze of lemon, please.", translation: "只要挤点柠檬汁，谢谢。", note: "柠檬汁调味。" },
    { id: "restaurant-14", speaker: "Server", text: "Noted. And would you like a side of rice or potatoes?", translation: "记下了。配米饭还是土豆？", note: "询问配菜。" },
    { id: "restaurant-15", speaker: "Customer", text: "Rice, please.", translation: "米饭，谢谢。", note: "选择配菜。" },
    { id: "restaurant-16", speaker: "Server", text: "Great. Anything to drink?", translation: "好的。喝点什么？", note: "询问饮品。" },
    { id: "restaurant-17", speaker: "Customer", text: "A glass of white wine, please.", translation: "一杯白葡萄酒，谢谢。", note: "点酒。" },
    { id: "restaurant-18", speaker: "Server", text: "We have a nice Chardonnay that pairs well with salmon.", translation: "我们有款不错的霞多丽，搭配三文鱼很搭。", note: "推荐酒水。" },
    { id: "restaurant-19", speaker: "Customer", text: "That sounds perfect. I'll have that.", translation: "听起来完美。我要这个。", note: "接受推荐。" },
    { id: "restaurant-20", speaker: "Server", text: "Wonderful. I'll put your order in right away.", translation: "太好了。我马上为您下单。", note: "确认下单。" },
    { id: "restaurant-21", speaker: "Customer", text: "Thank you. How long will the food take?", translation: "谢谢。食物要等多久？", note: "询问上菜时间。" },
    { id: "restaurant-22", speaker: "Server", text: "About fifteen to twenty minutes. Enjoy your salad while you wait.", translation: "大约十五到二十分钟。等餐时享用沙拉。", note: "告知等待时间。" },
    { id: "restaurant-23", speaker: "Customer", text: "Sounds good. I'll start with the salad then.", translation: "好的。那我先吃沙拉。", note: "同意等待。" },
    { id: "restaurant-24", speaker: "Server", text: "I'll be back shortly with your salad and water.", translation: "我很快拿沙拉和水回来。", note: "告知返回时间。" },
    { id: "restaurant-25", speaker: "Customer", text: "Thank you. That's very attentive service.", translation: "谢谢。服务真周到。", note: "表扬服务。" },
    { id: "restaurant-26", speaker: "Server", text: "You're welcome. Is there anything else I can get you?", translation: "不客气。还需要什么吗？", note: "询问其他需求。" },
    { id: "restaurant-27", speaker: "Customer", text: "No, that's all for now. Just the check when you're ready.", translation: "不用了。结账时叫我一声就行。", note: "要求结账。" },
    { id: "restaurant-28", speaker: "Server", text: "Of course. I'll bring the check shortly.", translation: "好的。我很快拿账单来。", note: "确认结账。" },
    { id: "restaurant-29", speaker: "Customer", text: "Thank you. This has been a lovely meal.", translation: "谢谢。这顿饭很愉快。", note: "评价用餐体验。" },
    { id: "restaurant-30", speaker: "Server", text: "I'm glad you enjoyed it. We hope to see you again soon.", translation: "很高兴您喜欢。期待下次光临。", note: "表达欢迎再次光临。" },
    { id: "restaurant-31", speaker: "Customer", text: "I'll definitely be back. Goodbye!", translation: "我一定会再来的。再见！", note: "告别。" },
    { id: "restaurant-32", speaker: "Server", text: "Goodbye! Have a great evening.", translation: "再见！祝您晚上愉快。", note: "回应告别。" },
    { id: "restaurant-33", speaker: "Customer", text: "Cheers!", translation: "干杯！", note: "致意。" },
    { id: "restaurant-34", speaker: "Server", text: "Cheers!", translation: "干杯！", note: "回礼。" },
    { id: "restaurant-35", speaker: "Customer", text: "Bye!", translation: "拜！", note: "告别。" },
    { id: "restaurant-36", speaker: "Server", text: "Bye!", translation: "拜！", note: "回应。" },
    { id: "restaurant-37", speaker: "Customer", text: "See you.", translation: "再见。", note: "道别。" },
    { id: "restaurant-38", speaker: "Server", text: "See you.", translation: "再见。", note: "回应。" },
    { id: "restaurant-39", speaker: "Customer", text: "Take care.", translation: "保重。", note: "道别。" },
    { id: "restaurant-40", speaker: "Server", text: "Take care.", translation: "保重。", note: "回应。" },
    { id: "restaurant-41", speaker: "Customer", text: "Alright.", translation: "好的。", note: "确认。" },
    { id: "restaurant-42", speaker: "Server", text: "Alright.", translation: "好的。", note: "确认。" },
    { id: "restaurant-43", speaker: "Customer", text: "Thanks.", translation: "谢谢。", note: "道谢。" },
    { id: "restaurant-44", speaker: "Server", text: "Anytime.", translation: "随时效劳。", note: "客气。" },
    { id: "restaurant-45", speaker: "Customer", text: "Talk soon.", translation: "回头聊。", note: "告别。" },
    { id: "restaurant-46", speaker: "Server", text: "Talk soon.", translation: "回头聊。", note: "回应。" },
    { id: "restaurant-47", speaker: "Customer", text: "Bye-bye.", translation: "拜拜。", note: "道别。" },
    { id: "restaurant-48", speaker: "Server", text: "Bye-bye.", translation: "拜拜。", note: "回应。" },
    { id: "restaurant-49", speaker: "Customer", text: "Cheers!", translation: "干杯！", note: "致意。" },
    { id: "restaurant-50", speaker: "Server", text: "Cheers!", translation: "干杯！", note: "回礼。" },
    { id: "restaurant-51", speaker: "Customer", text: "By the way, I wanted to ask you about the menu.", translation: "顺便问，我想问你关于菜单的事。", note: "询问话题" },
    { id: "restaurant-52", speaker: "Server", text: "I have been thinking about the specials lately.", translation: "我最近一直在考虑特色菜。", note: "表达想法" },
    { id: "restaurant-53", speaker: "Customer", text: "Do you have any thoughts on the dessert?", translation: "你对甜点有什么看法？", note: "征求意见" },
    { id: "restaurant-54", speaker: "Server", text: "By the way, I wanted to ask you about the wine list.", translation: "顺便问，我想问你关于酒单的事。", note: "询问话题" },
    { id: "restaurant-55", speaker: "Customer", text: "I have been thinking about the appetizers lately.", translation: "我最近一直在考虑开胃菜。", note: "表达想法" },
    { id: "restaurant-56", speaker: "Server", text: "Do you have any thoughts on the main course?", translation: "你对主菜有什么看法？", note: "征求意见" },
    { id: "restaurant-57", speaker: "Customer", text: "By the way, I wanted to ask you about the service.", translation: "顺便问，我想问你关于服务的事。", note: "询问话题" },
    { id: "restaurant-58", speaker: "Server", text: "I have been thinking about the atmosphere lately.", translation: "我最近一直在考虑氛围。", note: "表达想法" },
    { id: "restaurant-59", speaker: "Customer", text: "Do you have any thoughts on the price?", translation: "你对价格有什么看法？", note: "征求意见" },
    { id: "restaurant-60", speaker: "Server", text: "By the way, I wanted to ask you about the location.", translation: "顺便问，我想问你关于位置的事。", note: "询问话题" },
    { id: "restaurant-61", speaker: "Customer", text: "I have been thinking about the hours lately.", translation: "我最近一直在考虑营业时间。", note: "表达想法" },
    { id: "restaurant-62", speaker: "Server", text: "Do you have any thoughts on the staff?", translation: "你对员工有什么看法？", note: "征求意见" },
    { id: "restaurant-63", speaker: "Customer", text: "By the way, I wanted to ask you about the cleanliness.", translation: "顺便问，我想问你关于清洁的事。", note: "询问话题" },
    { id: "restaurant-64", speaker: "Server", text: "I have been thinking about the quality lately.", translation: "我最近一直在考虑品质。", note: "表达想法" },
    { id: "restaurant-65", speaker: "Customer", text: "Do you have any thoughts on the taste?", translation: "你对味道有什么看法？", note: "征求意见" },
    { id: "restaurant-66", speaker: "Server", text: "By the way, I wanted to ask you about the presentation.", translation: "顺便问，我想问你关于摆盘的事。", note: "询问话题" },
    { id: "restaurant-67", speaker: "Customer", text: "I have been thinking about the portions lately.", translation: "我最近一直在考虑份量。", note: "表达想法" },
    { id: "restaurant-68", speaker: "Server", text: "Do you have any thoughts on the ingredients?", translation: "你对食材有什么看法？", note: "征求意见" },
    { id: "restaurant-69", speaker: "Customer", text: "By the way, I wanted to ask you about the cooking method.", translation: "顺便问，我想问你关于烹饪方式的事。", note: "询问话题" },
    { id: "restaurant-70", speaker: "Server", text: "I have been thinking about the seasoning lately.", translation: "我最近一直在考虑调味。", note: "表达想法" },
    { id: "restaurant-71", speaker: "Customer", text: "Do you have any thoughts on the texture?", translation: "你对口感有什么看法？", note: "征求意见" },
    { id: "restaurant-72", speaker: "Server", text: "By the way, I wanted to ask you about the temperature.", translation: "顺便问，我想问你关于温度的事。", note: "询问话题" },
    { id: "restaurant-73", speaker: "Customer", text: "I have been thinking about the freshness lately.", translation: "我最近一直在考虑新鲜度。", note: "表达想法" },
    { id: "restaurant-74", speaker: "Server", text: "Do you have any thoughts on the origin?", translation: "你对产地有什么看法？", note: "征求意见" },
    { id: "restaurant-75", speaker: "Customer", text: "By the way, I wanted to ask you about the brand.", translation: "顺便问，我想问你关于品牌的事。", note: "询问话题" },
    { id: "restaurant-76", speaker: "Server", text: "I have been thinking about the style lately.", translation: "我最近一直在考虑风格。", note: "表达想法" },
    { id: "restaurant-77", speaker: "Customer", text: "Do you have any thoughts on the technique?", translation: "你对技巧有什么看法？", note: "征求意见" },
    { id: "restaurant-78", speaker: "Server", text: "By the way, I wanted to ask you about the recipe.", translation: "顺便问，我想问你关于食谱的事。", note: "询问话题" },
    { id: "restaurant-79", speaker: "Customer", text: "I have been thinking about the flavor lately.", translation: "我最近一直在考虑风味。", note: "表达想法" },
    { id: "restaurant-80", speaker: "Server", text: "Do you have any thoughts on the aroma?", translation: "你对香气有什么看法？", note: "征求意见" },
    { id: "restaurant-81", speaker: "Customer", text: "By the way, I wanted to ask you about the color.", translation: "顺便问，我想问你关于颜色的事。", note: "询问话题" },
    { id: "restaurant-82", speaker: "Server", text: "I have been thinking about the shape lately.", translation: "我最近一直在考虑形状。", note: "表达想法" },
    { id: "restaurant-83", speaker: "Customer", text: "Do you have any thoughts on the size?", translation: "你对大小有什么看法？", note: "征求意见" },
    { id: "restaurant-84", speaker: "Server", text: "By the way, I wanted to ask you about the weight.", translation: "顺便问，我想问你关于重量的事。", note: "询问话题" },
    { id: "restaurant-85", speaker: "Customer", text: "I have been thinking about the volume lately.", translation: "我最近一直在考虑容量。", note: "表达想法" },
    { id: "restaurant-86", speaker: "Server", text: "Do you have any thoughts on the density?", translation: "你对密度有什么看法？", note: "征求意见" },
    { id: "restaurant-87", speaker: "Customer", text: "By the way, I wanted to ask you about the consistency.", translation: "顺便问，我想问你关于质地的事。", note: "询问话题" },
    { id: "restaurant-88", speaker: "Server", text: "I have been thinking about the viscosity lately.", translation: "我最近一直在考虑黏度。", note: "表达想法" },
    { id: "restaurant-89", speaker: "Customer", text: "Do you have any thoughts on the elasticity?", translation: "你对弹性有什么看法？", note: "征求意见" },
    { id: "restaurant-90", speaker: "Server", text: "By the way, I wanted to ask you about the crunchiness.", translation: "顺便问，我想问你关于脆度的事。", note: "询问话题" },
    { id: "restaurant-91", speaker: "Customer", text: "I have been thinking about the softness lately.", translation: "我最近一直在考虑软度。", note: "表达想法" },
    { id: "restaurant-92", speaker: "Server", text: "Do you have any thoughts on the hardness?", translation: "你对硬度有什么看法？", note: "征求意见" },
    { id: "restaurant-93", speaker: "Customer", text: "By the way, I wanted to ask you about the smoothness.", translation: "顺便问，我想问你关于光滑度的事。", note: "询问话题" },
    { id: "restaurant-94", speaker: "Server", text: "I have been thinking about the roughness lately.", translation: "我最近一直在考虑粗糙度。", note: "表达想法" },
    { id: "restaurant-95", speaker: "Customer", text: "Do you have any thoughts on the thickness?", translation: "你对厚度有什么看法？", note: "征求意见" },
    { id: "restaurant-96", speaker: "Server", text: "By the way, I wanted to ask you about the thinness.", translation: "顺便问，我想问你关于薄度的事。", note: "询问话题" },
    { id: "restaurant-97", speaker: "Customer", text: "I have been thinking about the width lately.", translation: "我最近一直在考虑宽度。", note: "表达想法" },
    { id: "restaurant-98", speaker: "Server", text: "Do you have any thoughts on the length?", translation: "你对长度有什么看法？", note: "征求意见" },
    { id: "restaurant-99", speaker: "Customer", text: "By the way, I wanted to ask you about the height.", translation: "顺便问，我想问你关于高度的事。", note: "询问话题" },
    { id: "restaurant-100", speaker: "Server", text: "I have been thinking about the depth lately.", translation: "我最近一直在考虑深度。", note: "表达想法" },
  ],"""

# Replace restaurant scene
restaurant_pattern = r'  restaurant: \[\n(?:    \{ id: "restaurant-1"[^\n]*\n(?:    [^\n]*\n)*?    \{ id: "restaurant-40"[^\n]*\n)\s*\],'
content = re.sub(restaurant_pattern, RESTAURANT_SCENE, content, 1, re.DOTALL)

print("Restaurant scene replaced successfully!")

with open("lib/data.ts", "w", encoding="utf-8") as f:
    f.write(content)

print("All scenes will be replaced in subsequent steps.")