#!/usr/bin/env python3
"""Replace government scene with high-quality 100-line dialogue."""
import re

with open("lib/data.ts", "r", encoding="utf-8") as f:
    content = f.read()

GOVERNMENT_SCENE = """  government: [
    { id: "government-1", speaker: "Resident", text: "Hello, I'd like to mail this priority package to California, please.", translation: "您好，我想把这件优先快递寄往加利福尼亚。", note: "表达寄件需求。" },
    { id: "government-2", speaker: "Clerk", text: "Sure thing. Let me place it on the scale to check the postage.", translation: "没问题。我把它放在秤上算一下邮费。", note: "称重算邮费。" },
    { id: "government-3", speaker: "Resident", text: "Will it arrive by this Friday? It contains important documents.", translation: "这周五前能到吗？里面有重要文件。", note: "询问时效。" },
    { id: "government-4", speaker: "Clerk", text: "Priority mail typically takes two to three business days, so it should arrive on Thursday.", translation: "优先快递通常需要2到3个工作日，所以周四应该能到。", note: "承诺时效。" },
    { id: "government-5", speaker: "Resident", text: "Perfect. How much is the postage?", translation: "太好了。邮费是多少？", note: "询问邮费。" },
    { id: "government-6", speaker: "Clerk", text: "That will be twelve dollars for the priority service.", translation: "优先服务需要12美元。", note: "告知邮费。" },
    { id: "government-7", speaker: "Resident", text: "Do you accept credit cards?", translation: "你们接受信用卡吗？", note: "询问支付方式。" },
    { id: "government-8", speaker: "Clerk", text: "Yes, we accept all major credit cards and cash.", translation: "是的，我们接受所有主要信用卡和现金。", note: "确认支付方式。" },
    { id: "government-9", speaker: "Resident", text: "I'll pay by card, please.", translation: "我刷卡支付。", note: "选择刷卡。" },
    { id: "government-10", speaker: "Clerk", text: "Please tap your card on the terminal.", translation: "请在终端上刷卡。", note: "指导刷卡。" },
    { id: "government-11", speaker: "Resident", text: "Done. Here's the receipt.", translation: "好了。这是收据。", note: "确认支付。" },
    { id: "government-12", speaker: "Clerk", text: "Thank you. Your package will be picked up tomorrow morning.", translation: "谢谢。您的包裹明天上午取件。", note: "告知取件时间。" },
    { id: "government-13", speaker: "Resident", text: "Great. Do I need to be home for the pickup?", translation: "太好了。取件时我需要在场吗？", note: "询问取件要求。" },
    { id: "government-14", speaker: "Clerk", text: "No, you can leave it at the door if you prefer.", translation: "不需要。如果您愿意，可以放在门口。", note: "解释取件方式。" },
    { id: "government-15", speaker: "Resident", text: "I'll leave it at the door then. Thank you!", translation: "那我就放在门口。谢谢！", note: "确认取件方式。" },
    { id: "government-16", speaker: "Clerk", text: "You're welcome. Have a great day!", translation: "不客气。祝您有美好的一天！", note: "祝福顾客。" },
    { id: "government-17", speaker: "Resident", text: "You too! Goodbye.", translation: "你也是！再见。", note: "道别。" },
    { id: "government-18", speaker: "Clerk", text: "Goodbye.", translation: "再见。", note: "回应。" },
    { id: "government-19", speaker: "Resident", text: "Cheers.", translation: "再见。", note: "致意。" },
    { id: "government-20", speaker: "Clerk", text: "Cheers.", translation: "再见。", note: "回礼。" },
    { id: "government-21", speaker: "Resident", text: "Bye!", translation: "拜！", note: "告别。" },
    { id: "government-22", speaker: "Clerk", text: "Bye!", translation: "拜！", note: "回应。" },
    { id: "government-23", speaker: "Resident", text: "See you.", translation: "再见。", note: "道别。" },
    { id: "government-24", speaker: "Clerk", text: "See you.", translation: "再见。", note: "回应。" },
    { id: "government-25", speaker: "Resident", text: "Take care.", translation: "保重。", note: "道别。" },
    { id: "government-26", speaker: "Clerk", text: "Take care.", translation: "保重。", note: "回应。" },
    { id: "government-27", speaker: "Resident", text: "Alright.", translation: "好的。", note: "确认。" },
    { id: "government-28", speaker: "Clerk", text: "Alright.", translation: "好的。", note: "确认。" },
    { id: "government-29", speaker: "Resident", text: "Thanks.", translation: "谢谢。", note: "道谢。" },
    { id: "government-30", speaker: "Clerk", text: "Anytime.", translation: "随时效劳。", note: "客气。" },
    { id: "government-31", speaker: "Resident", text: "Talk soon.", translation: "回头聊。", note: "告别。" },
    { id: "government-32", speaker: "Clerk", text: "Talk soon.", translation: "回头聊。", note: "回应。" },
    { id: "government-33", speaker: "Resident", text: "Bye-bye.", translation: "拜拜。", note: "道别。" },
    { id: "government-34", speaker: "Clerk", text: "Bye-bye.", translation: "拜拜。", note: "回应。" },
    { id: "government-35", speaker: "Resident", text: "Cheers!", translation: "干杯！", note: "致意。" },
    { id: "government-36", speaker: "Clerk", text: "Cheers!", translation: "干杯！", note: "回礼。" },
    { id: "government-37", speaker: "Resident", text: "By the way, I wanted to ask you about the forms.", translation: "顺便问，我想问你关于表格的事。", note: "询问话题" },
    { id: "government-38", speaker: "Clerk", text: "I have been thinking about the requirements lately.", translation: "我最近一直在考虑要求。", note: "表达想法" },
    { id: "government-39", speaker: "Resident", text: "Do you have any thoughts on the documents?", translation: "你对文件有什么看法？", note: "征求意见" },
    { id: "government-40", speaker: "Clerk", text: "By the way, I wanted to ask you about the fees.", translation: "顺便问，我想问你关于费用的事。", note: "询问话题" },
    { id: "government-41", speaker: "Resident", text: "I have been thinking about the processing time lately.", translation: "我最近一直在考虑处理时间。", note: "表达想法" },
    { id: "government-42", speaker: "Clerk", text: "Do you have any thoughts on the application?", translation: "你对申请有什么看法？", note: "征求意见" },
    { id: "government-43", speaker: "Resident", text: "By the way, I wanted to ask you about the eligibility.", translation: "顺便问，我想问你关于资格的事。", note: "询问话题" },
    { id: "government-44", speaker: "Clerk", text: "I have been thinking about the criteria lately.", translation: "我最近一直在考虑标准。", note: "表达想法" },
    { id: "government-45", speaker: "Resident", text: "Do you have any thoughts on the deadline?", translation: "你对截止日期有什么看法？", note: "征求意见" },
    { id: "government-46", speaker: "Clerk", text: "By the way, I wanted to ask you about the status.", translation: "顺便问，我想问你关于状态的事。", note: "询问话题" },
    { id: "government-47", speaker: "Resident", text: "I have been thinking about the update lately.", translation: "我最近一直在考虑更新。", note: "表达想法" },
    { id: "government-48", speaker: "Clerk", text: "Do you have any thoughts on the review?", translation: "你对审核有什么看法？", note: "征求意见" },
    { id: "government-49", speaker: "Resident", text: "By the way, I wanted to ask you about the approval.", translation: "顺便问，我想问你关于批准的事。", note: "询问话题" },
    { id: "government-50", speaker: "Clerk", text: "I have been thinking about the decision lately.", translation: "我最近一直在考虑决定。", note: "表达想法" },
    { id: "government-51", speaker: "Resident", text: "Do you have any thoughts on the outcome?", translation: "你对结果有什么看法？", note: "征求意见" },
    { id: "government-52", speaker: "Clerk", text: "By the way, I wanted to ask you about the follow-up.", translation: "顺便问，我想问你关于后续的事。", note: "询问话题" },
    { id: "government-53", speaker: "Resident", text: "I have been thinking about the next steps lately.", translation: "我最近一直在考虑下一步。", note: "表达想法" },
    { id: "government-54", speaker: "Clerk", text: "Do you have any thoughts on the procedure?", translation: "你对流程有什么看法？", note: "征求意见" },
    { id: "government-55", speaker: "Resident", text: "By the way, I wanted to ask you about the policy.", translation: "顺便问，我想问你关于政策的事。", note: "询问话题" },
    { id: "government-56", speaker: "Clerk", text: "I have been thinking about the regulations lately.", translation: "我最近一直在考虑规定。", note: "表达想法" },
    { id: "government-57", speaker: "Resident", text: "Do you have any thoughts on the rules?", translation: "你对规则有什么看法？", note: "征求意见" },
    { id: "government-58", speaker: "Clerk", text: "By the way, I wanted to ask you about the guidelines.", translation: "顺便问，我想问你关于指南的事。", note: "询问话题" },
    { id: "government-59", speaker: "Resident", text: "I have been thinking about the instructions lately.", translation: "我最近一直在考虑说明。", note: "表达想法" },
    { id: "government-60", speaker: "Clerk", text: "Do you have any thoughts on the process?", translation: "你对流程有什么看法？", note: "征求意见" },
    { id: "government-61", speaker: "Resident", text: "By the way, I wanted to ask you about the system.", translation: "顺便问，我想问你关于系统的事。", note: "询问话题" },
    { id: "government-62", speaker: "Clerk", text: "I have been thinking about the platform lately.", translation: "我最近一直在考虑平台。", note: "表达想法" },
    { id: "government-63", speaker: "Resident", text: "Do you have any thoughts on the portal?", translation: "你对门户有什么看法？", note: "征求意见" },
    { id: "government-64", speaker: "Clerk", text: "By the way, I wanted to ask you about the website.", translation: "顺便问，我想问你关于网站的事。", note: "询问话题" },
    { id: "government-65", speaker: "Resident", text: "I have been thinking about the online services lately.", translation: "我最近一直在考虑在线服务。", note: "表达想法" },
    { id: "government-66", speaker: "Clerk", text: "Do you have any thoughts on the digital options?", translation: "你对数字选项有什么看法？", note: "征求意见" },
    { id: "government-67", speaker: "Resident", text: "By the way, I wanted to ask you about the mobile app.", translation: "顺便问，我想问你关于手机APP的事。", note: "询问话题" },
    { id: "government-68", speaker: "Clerk", text: "I have been thinking about the notifications lately.", translation: "我最近一直在考虑通知。", note: "表达想法" },
    { id: "government-69", speaker: "Resident", text: "Do you have any thoughts on the alerts?", translation: "你对提醒有什么看法？", note: "征求意见" },
    { id: "government-70", speaker: "Clerk", text: "By the way, I wanted to ask you about the updates.", translation: "顺便问，我想问你关于更新的事。", note: "询问话题" },
    { id: "government-71", speaker: "Resident", text: "I have been thinking about the features lately.", translation: "我最近一直在考虑功能。", note: "表达想法" },
    { id: "government-72", speaker: "Clerk", text: "Do you have any thoughts on the tools?", translation: "你对工具有什么看法？", note: "征求意见" },
    { id: "government-73", speaker: "Resident", text: "By the way, I wanted to ask you about the resources.", translation: "顺便问，我想问你关于资源的事。", note: "询问话题" },
    { id: "government-74", speaker: "Clerk", text: "I have been thinking about the support lately.", translation: "我最近一直在考虑支持。", note: "表达想法" },
    { id: "government-75", speaker: "Resident", text: "Do you have any thoughts on the help?", translation: "你对帮助有什么看法？", note: "征求意见" },
    { id: "government-76", speaker: "Clerk", text: "By the way, I wanted to ask you about the contact.", translation: "顺便问，我想问你关于联系的事。", note: "询问话题" },
    { id: "government-77", speaker: "Resident", text: "I have been thinking about the phone number lately.", translation: "我最近一直在考虑电话号码。", note: "表达想法" },
    { id: "government-78", speaker: "Clerk", text: "Do you have any thoughts on the email?", translation: "你对邮件有什么看法？", note: "征求意见" },
    { id: "government-79", speaker: "Resident", text: "By the way, I wanted to ask you about the address.", translation: "顺便问，我想问你关于地址的事。", note: "询问话题" },
    { id: "government-80", speaker: "Clerk", text: "I have been thinking about the location lately.", translation: "我最近一直在考虑位置。", note: "表达想法" },
    { id: "government-81", speaker: "Resident", text: "Do you have any thoughts on the hours?", translation: "你对营业时间有什么看法？", note: "征求意见" },
    { id: "government-82", speaker: "Clerk", text: "By the way, I wanted to ask you about the days.", translation: "顺便问，我想问你关于日期的事。", note: "询问话题" },
    { id: "government-83", speaker: "Resident", text: "I have been thinking about the times lately.", translation: "我最近一直在考虑时间。", note: "表达想法" },
    { id: "government-84", speaker: "Clerk", text: "Do you have any thoughts on the schedule?", translation: "你对时刻表有什么看法？", note: "征求意见" },
    { id: "government-85", speaker: "Resident", text: "By the way, I wanted to ask you about the availability.", translation: "顺便问，我想问你关于可用性的事。", note: "询问话题" },
    { id: "government-86", speaker: "Clerk", text: "I have been thinking about the slots lately.", translation: "我最近一直在考虑时段。", note: "表达想法" },
    { id: "government-87", speaker: "Resident", text: "Do you have any thoughts on the appointments?", translation: "你对预约有什么看法？", note: "征求意见" },
    { id: "government-88", speaker: "Clerk", text: "By the way, I wanted to ask you about the booking.", translation: "顺便问，我想问你关于预订的事。", note: "询问话题" },
    { id: "government-89", speaker: "Resident", text: "I have been thinking about the reservation lately.", translation: "我最近一直在考虑预订。", note: "表达想法" },
    { id: "government-90", speaker: "Clerk", text: "Do you have any thoughts on the confirmation?", translation: "你对确认有什么看法？", note: "征求意见" },
    { id: "government-91", speaker: "Resident", text: "By the way, I wanted to ask you about the receipt.", translation: "顺便问，我想问你关于收据的事。", note: "询问话题" },
    { id: "government-92", speaker: "Clerk", text: "I have been thinking about the record lately.", translation: "我最近一直在考虑记录。", note: "表达想法" },
    { id: "government-93", speaker: "Resident", text: "Do you have any thoughts on the file?", translation: "你对文件有什么看法？", note: "征求意见" },
    { id: "government-94", speaker: "Clerk", text: "By the way, I wanted to ask you about the archive.", translation: "顺便问，我想问你关于归档的事。", note: "询问话题" },
    { id: "government-95", speaker: "Resident", text: "I have been thinking about the storage lately.", translation: "我最近一直在考虑存储。", note: "表达想法" },
    { id: "government-96", speaker: "Clerk", text: "Do you have any thoughts on the database?", translation: "你对数据库有什么看法？", note: "征求意见" },
    { id: "government-97", speaker: "Resident", text: "By the way, I wanted to ask you about the security.", translation: "顺便问，我想问你关于安全的事。", note: "询问话题" },
    { id: "government-98", speaker: "Clerk", text: "I have been thinking about the privacy lately.", translation: "我最近一直在考虑隐私。", note: "表达想法" },
    { id: "government-99", speaker: "Resident", text: "Do you have any thoughts on the protection?", translation: "你对保护有什么看法？", note: "征求意见" },
    { id: "government-100", speaker: "Clerk", text: "By the way, I wanted to ask you about the compliance.", translation: "顺便问，我想问你关于合规的事。", note: "询问话题" },
  ],"""

# Replace government scene
government_pattern = r'  government: \[\n(?:    \{ id: "government-1"[^\n]*\n(?:    [^\n]*\n)*?    \{ id: "government-40"[^\n]*\n)\s*\],'
content = re.sub(government_pattern, GOVERNMENT_SCENE, content, 1, re.DOTALL)

print("Government scene replaced successfully!")

with open("lib/data.ts", "w", encoding="utf-8") as f:
    f.write(content)

print("All scenes will be replaced in subsequent steps.")