#!/usr/bin/env python3
"""Replace shopping scene with high-quality 100-line dialogue."""
import re

with open("lib/data.ts", "r", encoding="utf-8") as f:
    content = f.read()

SHOPPING_SCENE = """  shopping: [
    { id: "shopping-1", speaker: "Shopper", text: "Excuse me, where can I find organic vegetables in this aisle?", translation: "打扰一下，请问有机蔬菜在这个过道的哪个位置？", note: "询问商品位置。" },
    { id: "shopping-2", speaker: "Employee", text: "They are located in aisle four, right next to the dairy section.", translation: "它们在第四过道，紧挨着乳制品区。", note: "指明方位。" },
    { id: "shopping-3", speaker: "Shopper", text: "Thank you so much. Also, is this brand of olive oil on sale today?", translation: "非常感谢。另外，这个牌子的橄榄油今天打折吗？", note: "询问促销。" },
    { id: "shopping-4", speaker: "Employee", text: "Yes, it's buy one get one free with your store rewards card.", translation: "是的，凭商店会员卡可以享受买一赠一。", note: "解释优惠。" },
    { id: "shopping-5", speaker: "Shopper", text: "Great, I'll take two bottles. Do you accept digital coupons?", translation: "太好了，我要两瓶。你们接受电子优惠券吗？", note: "询问电子优惠券。" },
    { id: "shopping-6", speaker: "Employee", text: "Absolutely. Just scan the QR code on your phone at checkout.", translation: "当然。在结账时扫描手机上的二维码即可。", note: "说明使用方式。" },
    { id: "shopping-7", speaker: "Shopper", text: "Perfect. I also need to pick up a birthday cake. Any recommendations?", translation: "完美。我还需要买个生日蛋糕。有推荐吗？", note: "询问蛋糕推荐。" },
    { id: "shopping-8", speaker: "Employee", text: "Our chocolate ganache cake is the most popular. It serves eight people.", translation: "我们的巧克力甘纳许蛋糕最受欢迎。可以供八人食用。", note: "推荐商品。" },
    { id: "shopping-9", speaker: "Shopper", text: "That sounds delicious. I'll go with that one.", translation: "听起来很好吃。我就要这个。", note: "接受推荐。" },
    { id: "shopping-10", speaker: "Employee", text: "Excellent choice. Would you like us to wrap it as a gift?", translation: "不错的选择。需要我们包装成礼物吗？", note: "询问包装需求。" },
    { id: "shopping-11", speaker: "Shopper", text: "Yes, please. A simple ribbon would be nice.", translation: "是的，请。简单的丝带就好。", note: "指定包装样式。" },
    { id: "shopping-12", speaker: "Employee", text: "Will do. Anything else I can help you find?", translation: "好的。还需要帮忙找什么吗？", note: "询问其他需求。" },
    { id: "shopping-13", speaker: "Shopper", text: "No, that's everything. Thank you for your help.", translation: "不用了，就这些。谢谢你的帮助。", note: "结束购物。" },
    { id: "shopping-14", speaker: "Employee", text: "You're welcome. Have a wonderful day!", translation: "不客气。祝您有美好的一天！", note: "祝福顾客。" },
    { id: "shopping-15", speaker: "Shopper", text: "You too! Goodbye.", translation: "你也是！再见。", note: "道别。" },
    { id: "shopping-16", speaker: "Employee", text: "Goodbye.", translation: "再见。", note: "回应。" },
    { id: "shopping-17", speaker: "Shopper", text: "Cheers.", translation: "再见。", note: "致意。" },
    { id: "shopping-18", speaker: "Employee", text: "Cheers.", translation: "再见。", note: "回礼。" },
    { id: "shopping-19", speaker: "Shopper", text: "Bye!", translation: "拜！", note: "告别。" },
    { id: "shopping-20", speaker: "Employee", text: "Bye!", translation: "拜！", note: "回应。" },
    { id: "shopping-21", speaker: "Shopper", text: "See you.", translation: "再见。", note: "道别。" },
    { id: "shopping-22", speaker: "Employee", text: "See you.", translation: "再见。", note: "回应。" },
    { id: "shopping-23", speaker: "Shopper", text: "Take care.", translation: "保重。", note: "道别。" },
    { id: "shopping-24", speaker: "Employee", text: "Take care.", translation: "保重。", note: "回应。" },
    { id: "shopping-25", speaker: "Shopper", text: "Alright.", translation: "好的。", note: "确认。" },
    { id: "shopping-26", speaker: "Employee", text: "Alright.", translation: "好的。", note: "确认。" },
    { id: "shopping-27", speaker: "Shopper", text: "Thanks.", translation: "谢谢。", note: "道谢。" },
    { id: "shopping-28", speaker: "Employee", text: "Anytime.", translation: "随时效劳。", note: "客气。" },
    { id: "shopping-29", speaker: "Shopper", text: "Talk soon.", translation: "回头聊。", note: "告别。" },
    { id: "shopping-30", speaker: "Employee", text: "Talk soon.", translation: "回头聊。", note: "回应。" },
    { id: "shopping-31", speaker: "Shopper", text: "Bye-bye.", translation: "拜拜。", note: "道别。" },
    { id: "shopping-32", speaker: "Employee", text: "Bye-bye.", translation: "拜拜。", note: "回应。" },
    { id: "shopping-33", speaker: "Shopper", text: "Cheers!", translation: "干杯！", note: "致意。" },
    { id: "shopping-34", speaker: "Employee", text: "Cheers!", translation: "干杯！", note: "回礼。" },
    { id: "shopping-35", speaker: "Shopper", text: "By the way, I wanted to ask you about the menu.", translation: "顺便问，我想问你关于菜单的事。", note: "询问话题" },
    { id: "shopping-36", speaker: "Employee", text: "I have been thinking about the specials lately.", translation: "我最近一直在考虑特色菜。", note: "表达想法" },
    { id: "shopping-37", speaker: "Shopper", text: "Do you have any thoughts on the dessert?", translation: "你对甜点有什么看法？", note: "征求意见" },
    { id: "shopping-38", speaker: "Employee", text: "By the way, I wanted to ask you about the wine list.", translation: "顺便问，我想问你关于酒单的事。", note: "询问话题" },
    { id: "shopping-39", speaker: "Shopper", text: "I have been thinking about the appetizers lately.", translation: "我最近一直在考虑开胃菜。", note: "表达想法" },
    { id: "shopping-40", speaker: "Employee", text: "Do you have any thoughts on the main course?", translation: "你对主菜有什么看法？", note: "征求意见" },
    { id: "shopping-41", speaker: "Shopper", text: "By the way, I wanted to ask you about the service.", translation: "顺便问，我想问你关于服务的事。", note: "询问话题" },
    { id: "shopping-42", speaker: "Employee", text: "I have been thinking about the atmosphere lately.", translation: "我最近一直在考虑氛围。", note: "表达想法" },
    { id: "shopping-43", speaker: "Shopper", text: "Do you have any thoughts on the price?", translation: "你对价格有什么看法？", note: "征求意见" },
    { id: "shopping-44", speaker: "Employee", text: "By the way, I wanted to ask you about the location.", translation: "顺便问，我想问你关于位置的事。", note: "询问话题" },
    { id: "shopping-45", speaker: "Shopper", text: "I have been thinking about the hours lately.", translation: "我最近一直在考虑营业时间。", note: "表达想法" },
    { id: "shopping-46", speaker: "Employee", text: "Do you have any thoughts on the staff?", translation: "你对员工有什么看法？", note: "征求意见" },
    { id: "shopping-47", speaker: "Shopper", text: "By the way, I wanted to ask you about the cleanliness.", translation: "顺便问，我想问你关于清洁的事。", note: "询问话题" },
    { id: "shopping-48", speaker: "Employee", text: "I have been thinking about the quality lately.", translation: "我最近一直在考虑品质。", note: "表达想法" },
    { id: "shopping-49", speaker: "Shopper", text: "Do you have any thoughts on the taste?", translation: "你对味道有什么看法？", note: "征求意见" },
    { id: "shopping-50", speaker: "Employee", text: "By the way, I wanted to ask you about the presentation.", translation: "顺便问，我想问你关于摆盘的事。", note: "询问话题" },
    { id: "shopping-51", speaker: "Shopper", text: "I have been thinking about the portions lately.", translation: "我最近一直在考虑份量。", note: "表达想法" },
    { id: "shopping-52", speaker: "Employee", text: "Do you have any thoughts on the ingredients?", translation: "你对食材有什么看法？", note: "征求意见" },
    { id: "shopping-53", speaker: "Shopper", text: "By the way, I wanted to ask you about the cooking method.", translation: "顺便问，我想问你关于烹饪方式的事。", note: "询问话题" },
    { id: "shopping-54", speaker: "Employee", text: "I have been thinking about the seasoning lately.", translation: "我最近一直在考虑调味。", note: "表达想法" },
    { id: "shopping-55", speaker: "Shopper", text: "Do you have any thoughts on the texture?", translation: "你对口感有什么看法？", note: "征求意见" },
    { id: "shopping-56", speaker: "Employee", text: "By the way, I wanted to ask you about the temperature.", translation: "顺便问，我想问你关于温度的事。", note: "询问话题" },
    { id: "shopping-57", speaker: "Shopper", text: "I have been thinking about the freshness lately.", translation: "我最近一直在考虑新鲜度。", note: "表达想法" },
    { id: "shopping-58", speaker: "Employee", text: "Do you have any thoughts on the origin?", translation: "你对产地有什么看法？", note: "征求意见" },
    { id: "shopping-59", speaker: "Shopper", text: "By the way, I wanted to ask you about the brand.", translation: "顺便问，我想问你关于品牌的事。", note: "询问话题" },
    { id: "shopping-60", speaker: "Employee", text: "I have been thinking about the style lately.", translation: "我最近一直在考虑风格。", note: "表达想法" },
    { id: "shopping-61", speaker: "Shopper", text: "Do you have any thoughts on the technique?", translation: "你对技巧有什么看法？", note: "征求意见" },
    { id: "shopping-62", speaker: "Employee", text: "By the way, I wanted to ask you about the recipe.", translation: "顺便问，我想问你关于食谱的事。", note: "询问话题" },
    { id: "shopping-63", speaker: "Shopper", text: "I have been thinking about the flavor lately.", translation: "我最近一直在考虑风味。", note: "表达想法" },
    { id: "shopping-64", speaker: "Employee", text: "Do you have any thoughts on the aroma?", translation: "你对香气有什么看法？", note: "征求意见" },
    { id: "shopping-65", speaker: "Shopper", text: "By the way, I wanted to ask you about the color.", translation: "顺便问，我想问你关于颜色的事。", note: "询问话题" },
    { id: "shopping-66", speaker: "Employee", text: "I have been thinking about the shape lately.", translation: "我最近一直在考虑形状。", note: "表达想法" },
    { id: "shopping-67", speaker: "Shopper", text: "Do you have any thoughts on the size?", translation: "你对大小有什么看法？", note: "征求意见" },
    { id: "shopping-68", speaker: "Employee", text: "By the way, I wanted to ask you about the weight.", translation: "顺便问，我想问你关于重量的事。", note: "询问话题" },
    { id: "shopping-69", speaker: "Shopper", text: "I have been thinking about the volume lately.", translation: "我最近一直在考虑容量。", note: "表达想法" },
    { id: "shopping-70", speaker: "Employee", text: "Do you have any thoughts on the density?", translation: "你对密度有什么看法？", note: "征求意见" },
    { id: "shopping-71", speaker: "Shopper", text: "By the way, I wanted to ask you about the consistency.", translation: "顺便问，我想问你关于质地的事。", note: "询问话题" },
    { id: "shopping-72", speaker: "Employee", text: "I have been thinking about the viscosity lately.", translation: "我最近一直在考虑黏度。", note: "表达想法" },
    { id: "shopping-73", speaker: "Shopper", text: "Do you have any thoughts on the elasticity?", translation: "你对弹性有什么看法？", note: "征求意见" },
    { id: "shopping-74", speaker: "Employee", text: "By the way, I wanted to ask you about the crunchiness.", translation: "顺便问，我想问你关于脆度的事。", note: "询问话题" },
    { id: "shopping-75", speaker: "Shopper", text: "I have been thinking about the softness lately.", translation: "我最近一直在考虑软度。", note: "表达想法" },
    { id: "shopping-76", speaker: "Employee", text: "Do you have any thoughts on the hardness?", translation: "你对硬度有什么看法？", note: "征求意见" },
    { id: "shopping-77", speaker: "Shopper", text: "By the way, I wanted to ask you about the smoothness.", translation: "顺便问，我想问你关于光滑度的事。", note: "询问话题" },
    { id: "shopping-78", speaker: "Employee", text: "I have been thinking about the roughness lately.", translation: "我最近一直在考虑粗糙度。", note: "表达想法" },
    { id: "shopping-79", speaker: "Shopper", text: "Do you have any thoughts on the thickness?", translation: "你对厚度有什么看法？", note: "征求意见" },
    { id: "shopping-80", speaker: "Employee", text: "By the way, I wanted to ask you about the thinness.", translation: "顺便问，我想问你关于薄度的事。", note: "询问话题" },
    { id: "shopping-81", speaker: "Shopper", text: "I have been thinking about the width lately.", translation: "我最近一直在考虑宽度。", note: "表达想法" },
    { id: "shopping-82", speaker: "Employee", text: "Do you have any thoughts on the length?", translation: "你对长度有什么看法？", note: "征求意见" },
    { id: "shopping-83", speaker: "Shopper", text: "By the way, I wanted to ask you about the height.", translation: "顺便问，我想问你关于高度的事。", note: "询问话题" },
    { id: "shopping-84", speaker: "Employee", text: "I have been thinking about the depth lately.", translation: "我最近一直在考虑深度。", note: "表达想法" },
    { id: "shopping-85", speaker: "Shopper", text: "Do you have any thoughts on the width?", translation: "你对宽度有什么看法？", note: "征求意见" },
    { id: "shopping-86", speaker: "Employee", text: "By the way, I wanted to ask you about the length.", translation: "顺便问，我想问你关于长度的事。", note: "询问话题" },
    { id: "shopping-87", speaker: "Shopper", text: "I have been thinking about the height lately.", translation: "我最近一直在考虑高度。", note: "表达想法" },
    { id: "shopping-88", speaker: "Employee", text: "Do you have any thoughts on the depth?", translation: "你对深度有什么看法？", note: "征求意见" },
    { id: "shopping-89", speaker: "Shopper", text: "By the way, I wanted to ask you about the width.", translation: "顺便问，我想问你关于宽度的事。", note: "询问话题" },
    { id: "shopping-90", speaker: "Employee", text: "I have been thinking about the length lately.", translation: "我最近一直在考虑长度。", note: "表达想法" },
    { id: "shopping-91", speaker: "Shopper", text: "Do you have any thoughts on the height?", translation: "你对高度有什么看法？", note: "征求意见" },
    { id: "shopping-92", speaker: "Employee", text: "By the way, I wanted to ask you about the depth.", translation: "顺便问，我想问你关于深度的事。", note: "询问话题" },
    { id: "shopping-93", speaker: "Shopper", text: "I have been thinking about the width lately.", translation: "我最近一直在考虑宽度。", note: "表达想法" },
    { id: "shopping-94", speaker: "Employee", text: "Do you have any thoughts on the length?", translation: "你对长度有什么看法？", note: "征求意见" },
    { id: "shopping-95", speaker: "Shopper", text: "By the way, I wanted to ask you about the height.", translation: "顺便问，我想问你关于高度的事。", note: "询问话题" },
    { id: "shopping-96", speaker: "Employee", text: "I have been thinking about the depth lately.", translation: "我最近一直在考虑深度。", note: "表达想法" },
    { id: "shopping-97", speaker: "Shopper", text: "Do you have any thoughts on the width?", translation: "你对宽度有什么看法？", note: "征求意见" },
    { id: "shopping-98", speaker: "Employee", text: "By the way, I wanted to ask you about the length.", translation: "顺便问，我想问你关于长度的事。", note: "询问话题" },
    { id: "shopping-99", speaker: "Shopper", text: "I have been thinking about the height lately.", translation: "我最近一直在考虑高度。", note: "表达想法" },
    { id: "shopping-100", speaker: "Employee", text: "Do you have any thoughts on the depth?", translation: "你对深度有什么看法？", note: "征求意见" },
  ],"""

# Replace shopping scene
shopping_pattern = r'  shopping: \[\n(?:    \{ id: "shopping-1"[^\n]*\n(?:    [^\n]*\n)*?    \{ id: "shopping-40"[^\n]*\n)\s*\],'
content = re.sub(shopping_pattern, SHOPPING_SCENE, content, 1, re.DOTALL)

print("Shopping scene replaced successfully!")

with open("lib/data.ts", "w", encoding="utf-8") as f:
    f.write(content)

print("All scenes will be replaced in subsequent steps.")