export type WordDefinition = { phonetic: string; meaning: string };

const WORDS: Record<string, WordDefinition> = {
  responsibilities: { phonetic: "/rɪˌspɒnsəˈbɪlətiz/", meaning: "责任；职责" },
  congratulations: { phonetic: "/kənˌɡrætʃəˈleɪʃnz/", meaning: "恭喜；祝贺" },
  authentication: { phonetic: "/ɔːˌθentɪˈkeɪʃn/", meaning: "身份验证；认证" },
  infrastructure: { phonetic: "/ˈɪnfrəstrʌktʃər/", meaning: "基础设施" },
  identification: { phonetic: "/aɪˌdentɪfɪˈkeɪʃn/", meaning: "身份证明；识别" },
  professionally: { phonetic: "/prəˈfeʃənəli/", meaning: "专业地" },
  transportation: { phonetic: "/ˌtrænspɔːrˈteɪʃn/", meaning: "交通；运输" },
  naturalization: { phonetic: "/ˌnætʃərəlaɪˈzeɪʃn/", meaning: "归化；入籍" },
  proprietorship: { phonetic: "/prəˈpraɪətərʃɪp/", meaning: "业主身份；独资经营" },
  establishments: { phonetic: "/ɪˈstæblɪʃmənts/", meaning: "企业；机构" },
  administrative: { phonetic: "/ədˈmɪnɪstrətɪv/", meaning: "行政的；管理的" },
  international: { phonetic: "/ˌɪntərˈnæʃnəl/", meaning: "国际的" },
  automatically: { phonetic: "/ˌɔːtəˈmætɪkli/", meaning: "自动地" },
  significantly: { phonetic: "/sɪɡˈnɪfɪkəntli/", meaning: "显著地" },
  approximately: { phonetic: "/əˈprɒksɪmətli/", meaning: "大约；近似" },
  contributions: { phonetic: "/ˌkɒntrɪˈbjuːʃnz/", meaning: "贡献；捐款" },
  architectural: { phonetic: "/ˌɑːrkɪˈtektʃərəl/", meaning: "建筑的；建筑学的" },
  unforgettable: { phonetic: "/ˌʌnfəˈɡetəbl/", meaning: "难忘的" },
  collaboration: { phonetic: "/kəˌlæbəˈreɪʃn/", meaning: "合作；协作" },
  communication: { phonetic: "/kəˌmjuːnɪˈkeɪʃn/", meaning: "沟通；交流" },
  investigating: { phonetic: "/ɪnˈvestɪɡeɪtɪŋ/", meaning: "调查；研究" },
  carbohydrates: { phonetic: "/ˌkɑːrboʊˈhaɪdreɪts/", meaning: "碳水化合物" },
  denominations: { phonetic: "/dɪˌnɒmɪˈneɪʃnz/", meaning: "面额；教派" },
  investigation: { phonetic: "/ɪnˌvestɪˈɡeɪʃn/", meaning: "调查；研究" },
  unfortunately: { phonetic: "/ʌnˈfɔːrtʃənətli/", meaning: "不幸地" },
  notifications: { phonetic: "/ˌnoʊtɪfɪˈkeɪʃnz/", meaning: "通知" },
  environmental: { phonetic: "/ɪnˌvaɪrənˈmentl/", meaning: "环境的" },
  comprehensive: { phonetic: "/ˌkɒmprɪˈhensɪv/", meaning: "综合的；全面的" },
  disbursements: { phonetic: "/dɪsˈbɜːrsmənts/", meaning: "支付；支出" },
  malfunctioned: { phonetic: "/ˌmælˈfʌŋkʃnd/", meaning: "发生故障的" },
  certification: { phonetic: "/ˌsɜːrtɪfɪˈkeɪʃn/", meaning: "认证；证书" },
  confirmation: { phonetic: "/ˌkɒnfərˈmeɪʃn/", meaning: "确认；证实" },
  requirements: { phonetic: "/rɪˈkwaɪəmənts/", meaning: "要求；必要条件" },
  neighborhood: { phonetic: "/ˈneɪbərhʊd/", meaning: "街区；社区" },
  occasionally: { phonetic: "/əˈkeɪʒənəli/", meaning: "偶尔地" },
  breathtaking: { phonetic: "/ˈbreθteɪkɪŋ/", meaning: "令人惊叹的" },
  professional: { phonetic: "/prəˈfeʃənəl/", meaning: "专业的；职业的" },
  conditioning: { phonetic: "/kənˈdɪʃnɪŋ/", meaning: "训练；调节" },
  construction: { phonetic: "/kənˈstrʌkʃn/", meaning: "建设；建造" },
  presentation: { phonetic: "/ˌpreznˈteɪʃn/", meaning: "演示；展示" },
  contribution: { phonetic: "/ˌkɒntrɪˈbjuːʃn/", meaning: "贡献" },
  authenticity: { phonetic: "/ˌɔːθenˈtɪsəti/", meaning: "真实性；可靠性" },
  registration: { phonetic: "/ˌredʒɪˈstreɪʃn/", meaning: "注册；登记" },
  independence: { phonetic: "/ˌɪndɪˈpendəns/", meaning: "独立；自主" },
  thanksgiving: { phonetic: "/ˌθæŋksˈɡɪvɪŋ/", meaning: "感恩节；感恩" },
  surprisingly: { phonetic: "/sərˈpraɪzɪŋli/", meaning: "令人惊讶地" },
  rechargeable: { phonetic: "/riːˈtʃɑːrdʒəbl/", meaning: "可充电的" },
  compartments: { phonetic: "/kəmˈpɑːrtmənts/", meaning: "隔间；舱" },
  stakeholders: { phonetic: "/ˈsteɪkhəʊldərz/", meaning: "利益相关者" },
  testimonials: { phonetic: "/ˌtestɪˈmoʊniəlz/", meaning: "推荐信；证明书" },
  achievements: { phonetic: "/əˈtʃiːvmənts/", meaning: "成就；成绩" },
  coordination: { phonetic: "/koʊˌɔːrdɪˈneɪʃn/", meaning: "协调；配合" },
  expectations: { phonetic: "/ˌekspekˈteɪʃnz/", meaning: "期望；期待" },
  refrigerator: { phonetic: "/rɪˈfrɪdʒəreɪtər/", meaning: "冰箱" },
  personalized: { phonetic: "/ˈpɜːrsənəlaɪzd/", meaning: "个性化的" },
  foundational: { phonetic: "/faʊnˈdeɪʃənəl/", meaning: "基础的；根本的" },
  conservative: { phonetic: "/kənˈsɜːrvətɪv/", meaning: "保守的；谨慎的" },
  transactions: { phonetic: "/trænˈzækʃnz/", meaning: "交易；事务" },
  alternatives: { phonetic: "/ɔːlˈtɜːrnətɪvz/", meaning: "替代方案" },
  refrigerated: { phonetic: "/rɪˈfrɪdʒəreɪtɪd/", meaning: "冷藏的" },
  cancellation: { phonetic: "/ˌkænsəˈleɪʃn/", meaning: "取消；撤销" },
  manufacturer: { phonetic: "/ˌmænjuˈfæktʃərər/", meaning: "制造商" },
  thoroughfare: { phonetic: "/ˈθʌrəfer/", meaning: "大道；主干道" },
  equalization: { phonetic: "/ɪˌkwəlaɪˈzeɪʃn/", meaning: "均衡化；均等化" },
  municipality: { phonetic: "/mjuːˌnɪsɪˈpæləti/", meaning: "市政当局；市" },
  organization: { phonetic: "/ˌɔːrɡənəˈzeɪʃn/", meaning: "组织；机构" },
  reinspection: { phonetic: "/riːɪnˈspekʃn/", meaning: "重新检查；复查" },
  certificates: { phonetic: "/sərˈtɪfɪkəts/", meaning: "证书；证明书" },
  unemployment: { phonetic: "/ˌʌnɪmˈplɔɪmənt/", meaning: "失业" },
  compensation: { phonetic: "/ˌkɒmpenˈseɪʃn/", meaning: "补偿；报酬" },
  practitioner: { phonetic: "/prækˈtɪʃənər/", meaning: "从业者；实践者" },
  governmental: { phonetic: "/ˌɡʌvərnˈmentl/", meaning: "政府的" },
  application: { phonetic: "/ˌæplɪˈkeɪʃn/", meaning: "申请；应用" },
  traditional: { phonetic: "/trəˈdɪʃnəl/", meaning: "传统的" },
  immediately: { phonetic: "/ɪˈmiːdiətli/", meaning: "立即；马上" },
  transaction: { phonetic: "/trænˈzækʃn/", meaning: "交易；业务" },
  residential: { phonetic: "/ˌrezɪˈdenʃl/", meaning: "住宅的；居住的" },
  temperature: { phonetic: "/ˈtemprətʃər/", meaning: "温度；体温" },
  eligibility: { phonetic: "/ˌelɪdʒəˈbɪləti/", meaning: "资格；合格性" },
  contactless: { phonetic: "/ˈkɒntæktləs/", meaning: "非接触的" },
  spreadsheet: { phonetic: "/ˈspredʃiːt/", meaning: "电子表格" },
  operational: { phonetic: "/ˌɒpəˈreɪʃnəl/", meaning: "运作的；操作的" },
  electricity: { phonetic: "/ɪˌlekˈtrɪsəti/", meaning: "电力；电" },
  underground: { phonetic: "/ˌʌndərˈɡraʊnd/", meaning: "地下的；地铁" },
  antibiotics: { phonetic: "/ˌæntibaɪˈɒtɪks/", meaning: "抗生素；抗菌素" },
  specialized: { phonetic: "/ˈspeʃəlaɪzd/", meaning: "专门的；专业的" },
  maintaining: { phonetic: "/meɪnˈteɪnɪŋ/", meaning: "维护；保养" },
  fingerprint: { phonetic: "/ˈfɪŋɡərprɪnt/", meaning: "指纹" },
  replacement: { phonetic: "/rɪˈpleɪsmənt/", meaning: "替换；代替品" },
  individuals: { phonetic: "/ˌɪndɪˈvɪdʒuəlz/", meaning: "个人；个体" },
  anniversary: { phonetic: "/ˌænɪˈvɜːrsəri/", meaning: "周年纪念日" },
  information: { phonetic: "/ˌɪnfərˈmeɪʃn/", meaning: "信息；资料" },
  enforcement: { phonetic: "/ɪnˈfɔːrsmənt/", meaning: "执行；强制" },
  vaccination: { phonetic: "/ˌvæksɪˈneɪʃn/", meaning: "疫苗接种" },
  consistency: { phonetic: "/kənˈsɪstənsi/", meaning: "一致性；连贯性" },
  therapeutic: { phonetic: "/ˌθerəˈpjuːtɪk/", meaning: "治疗的；疗效的" },
  documentary: { phonetic: "/ˌdɒkjuˈmentəri/", meaning: "纪录的；文件的" },
  immigration: { phonetic: "/ˌɪmɪˈɡreɪʃn/", meaning: "移民；入境" },
  sightseeing: { phonetic: "/ˈsaɪtsiːɪŋ/", meaning: "观光；游览" },
  transparent: { phonetic: "/trænsˈpærənt/", meaning: "透明的；清晰的" },
  convenience: { phonetic: "/kənˈviːniəns/", meaning: "便利；方便" },
  exhibitions: { phonetic: "/ˌeksɪˈbɪʃnz/", meaning: "展览；展示" },
  experiences: { phonetic: "/ɪkˈspɪəriənsɪz/", meaning: "经历；体验" },
  orientation: { phonetic: "/ˌɔːriənˈteɪʃn/", meaning: "方向；定位" },
  competitive: { phonetic: "/kəmˈpetətɪv/", meaning: "竞争的；有竞争力的" },
  performance: { phonetic: "/pərˈfɔːrməns/", meaning: "表现；性能" },
  challenging: { phonetic: "/ˈtʃælɪndʒɪŋ/", meaning: "有挑战性的" },
  development: { phonetic: "/dɪˈveləpmənt/", meaning: "发展；开发" },
  spontaneous: { phonetic: "/spɒnˈteɪniəs/", meaning: "自发的；自然的" },
  connections: { phonetic: "/kəˈnekʃnz/", meaning: "联系；连接" },
  exceptional: { phonetic: "/ɪkˈsepʃənəl/", meaning: "杰出的；例外的" },
  negotiation: { phonetic: "/nɪˌɡoʊʃiˈeɪʃn/", meaning: "谈判；协商" },
  responsible: { phonetic: "/rɪˈspɒnsəbl/", meaning: "负责任的" },
  thermometer: { phonetic: "/θərˈmɒmɪtər/", meaning: "温度计；体温计" },
  ineffective: { phonetic: "/ˌɪnɪˈfektɪv/", meaning: "无效的；不起作用的" },
  medications: { phonetic: "/ˌmedɪˈkeɪʃnz/", meaning: "药物；药品" },
  experienced: { phonetic: "/ɪkˈspɪəriənst/", meaning: "有经验的" },
  sensitivity: { phonetic: "/ˌsensəˈtɪvəti/", meaning: "敏感性；灵敏度" },
  overwhelmed: { phonetic: "/ˌoʊvərˈwɛlmd/", meaning: " overwhelmed；不知所措" },
  mindfulness: { phonetic: "/ˈmaɪndfəlnəs/", meaning: "正念；专注" },


  a: { phonetic: "/ə/", meaning: "一个；一" },
  an: { phonetic: "/ən/", meaning: "一个；一" },
  the: { phonetic: "/ðə/", meaning: "这；那；这些；那些" },
  i: { phonetic: "/aɪ/", meaning: "我" },
  "i've": { phonetic: "/aɪv/", meaning: "我已经；我一直" },
  "i'm": { phonetic: "/aɪm/", meaning: "我是" },
  "it's": { phonetic: "/ɪts/", meaning: "它是；这是" },
  you: { phonetic: "/juː/", meaning: "你；你们" },
  your: { phonetic: "/jʊr/", meaning: "你的；你们的" },
  we: { phonetic: "/wiː/", meaning: "我们" },
  they: { phonetic: "/ðeɪ/", meaning: "他们" },
  have: { phonetic: "/hæv/", meaning: "有；已经" },
  been: { phonetic: "/bɪn/", meaning: "是；一直处于" },
  what: { phonetic: "/wʌt/", meaning: "什么" },
  how: { phonetic: "/haʊ/", meaning: "怎样；如何" },
  are: { phonetic: "/ɑːr/", meaning: "是" },
  hi: { phonetic: "/haɪ/", meaning: "嗨；你好" },
  hello: { phonetic: "/həˈloʊ/", meaning: "你好" },
  nice: { phonetic: "/naɪs/", meaning: "友好的；不错的" },
  meet: { phonetic: "/miːt/", meaning: "遇见；见面" },
  today: { phonetic: "/təˈdeɪ/", meaning: "今天" },
  while: { phonetic: "/waɪl/", meaning: "一段时间；当……时" },
  well: { phonetic: "/wel/", meaning: "好；顺利地" },
  busy: { phonetic: "/ˈbɪzi/", meaning: "忙碌的" },
  work: { phonetic: "/wɜːrk/", meaning: "工作" },
  feeling: { phonetic: "/ˈfiːlɪŋ/", meaning: "感觉" },
  catch: { phonetic: "/kætʃ/", meaning: "赶上；叙旧" },
  soon: { phonetic: "/suːn/", meaning: "很快" },
  definitely: { phonetic: "/ˈdefɪnətli/", meaning: "当然；肯定地" },
  free: { phonetic: "/friː/", meaning: "空闲的；免费的" },
  weekend: { phonetic: "/ˌwiːkˈend/", meaning: "周末" },
  saturday: { phonetic: "/ˈsætərdeɪ/", meaning: "星期六" },
  afternoon: { phonetic: "/ˌæftərˈnuːn/", meaning: "下午" },
  works: { phonetic: "/wɜːrks/", meaning: "奏效；合适" },
  perfectly: { phonetic: "/ˈpɜːrfɪktli/", meaning: "完美地；完全地" },
  great: { phonetic: "/ɡreɪt/", meaning: "好的；伟大的" },
  "let's": { phonetic: "/lets/", meaning: "让我们" },
  cafe: { phonetic: "/kæˈfeɪ/", meaning: "咖啡馆" },
  downtown: { phonetic: "/ˈdaʊnˈtaʊn/", meaning: "市中心" },
  heard: { phonetic: "/hɜːrd/", meaning: "听说；听到" },
  things: { phonetic: "/θɪŋz/", meaning: "事情；事物" },
  coffee: { phonetic: "/ˈkɔːfi/", meaning: "咖啡" },
  disappointed: { phonetic: "/ˌdɪsəˈpɔɪntɪd/", meaning: "失望的" },
  shall: { phonetic: "/ʃæl/", meaning: "将；好吗" },
  say: { phonetic: "/seɪ/", meaning: "说；表示" },
  around: { phonetic: "/əˈraʊnd/", meaning: "大约；在周围" },
  looking: { phonetic: "/ˈlʊkɪŋ/", meaning: "期待；看" },
  forward: { phonetic: "/ˈfɔːrwərd/", meaning: "向前；期待" },
  productive: { phonetic: "/prəˈdʌktɪv/", meaning: "高效的" },
  enjoying: { phonetic: "/ɪnˈdʒɔɪɪŋ/", meaning: "享受" },
  lately: { phonetic: "/ˈleɪtli/", meaning: "最近" },
  taking: { phonetic: "/ˈteɪkɪŋ/", meaning: "参加；拿取" },
  photography: { phonetic: "/fəˈtɑːɡrəfi/", meaning: "摄影" },
  class: { phonetic: "/klæs/", meaning: "课程；班级" },
  fascinating: { phonetic: "/ˈfæsɪneɪtɪŋ/", meaning: "迷人的；很有趣的" },
  subjects: { phonetic: "/ˈsʌbdʒɪkts/", meaning: "主题；科目" },
  focus: { phonetic: "/ˈfoʊkəs/", meaning: "专注；焦点" },
  mostly: { phonetic: "/ˈmoʊstli/", meaning: "主要地" },
  street: { phonetic: "/striːt/", meaning: "街道" },
  architecture: { phonetic: "/ˈɑːrkɪtektʃər/", meaning: "建筑；建筑学" },
  city: { phonetic: "/ˈsɪti/", meaning: "城市" },
  urban: { phonetic: "/ˈɜːrbən/", meaning: "城市的" },
  life: { phonetic: "/laɪf/", meaning: "生活；生命" },
  requires: { phonetic: "/rɪˈkwaɪərz/", meaning: "需要" },
  timing: { phonetic: "/ˈtaɪmɪŋ/", meaning: "时机" },
  patience: { phonetic: "/ˈpeɪʃəns/", meaning: "耐心" },
  details: { phonetic: "/ˈdiːteɪlz/", meaning: "细节" },
  considered: { phonetic: "/kənˈsɪdərd/", meaning: "考虑过" },
  exhibiting: { phonetic: "/ɪɡˈzɪbɪtɪŋ/", meaning: "展出" },
  gallery: { phonetic: "/ˈɡæləri/", meaning: "画廊" },
  portfolio: { phonetic: "/pɔːrtˈfoʊlioʊ/", meaning: "作品集" },
  perspective: { phonetic: "/pərˈspektɪv/", meaning: "视角；观点" },
  encouragement: { phonetic: "/ɪnˈkɜːrɪdʒmənt/", meaning: "鼓励" },
  appreciate: { phonetic: "/əˈpriːʃieɪt/", meaning: "感激；欣赏" },
  travel: { phonetic: "/ˈtrævəl/", meaning: "旅行" },
  account: { phonetic: "/əˈkaʊnt/", meaning: "账户" },
  doctor: { phonetic: "/ˈdɑːktər/", meaning: "医生" },
  school: { phonetic: "/skuːl/", meaning: "学校" },
  welcome: { phonetic: "/ˈwelkəm/", meaning: "欢迎" },
  good: { phonetic: "/ɡʊd/", meaning: "好的" },
  morning: { phonetic: "/ˈmɔːrnɪŋ/", meaning: "早上" },
  please: { phonetic: "/pliːz/", meaning: "请" },
  thank: { phonetic: "/θæŋk/", meaning: "感谢" },
  water: { phonetic: "/ˈwɔːtər/", meaning: "水" },
  meeting: { phonetic: "/ˈmiːtɪŋ/", meaning: "会议" },
  payment: { phonetic: "/ˈpeɪmənt/", meaning: "支付" },
  appointment: { phonetic: "/əˈpɔɪntmənt/", meaning: "预约" },
  package: { phonetic: "/ˈpækɪdʒ/", meaning: "包裹" },
  teacher: { phonetic: "/ˈtiːtʃər/", meaning: "老师" },
  excuse: { phonetic: "/ɪkˈskjuːz/", meaning: "原谅；借口" },
  could: { phonetic: "/kʊd/", meaning: "能够（过去式）" },
  tell: { phonetic: "/tel/", meaning: "告诉" },
  central: { phonetic: "/ˈsentrəl/", meaning: "中心的" },
  station: { phonetic: "/ˈsteɪʃən/", meaning: "车站" },
  sure: { phonetic: "/ʃʊr/", meaning: "当然；确信" },
  take: { phonetic: "/teɪk/", meaning: "拿；花费" },
  subway: { phonetic: "/ˈsʌbweɪ/", meaning: "地铁" },
  line: { phonetic: "/laɪn/", meaning: "线；线路" },
  get: { phonetic: "/ɡet/", meaning: "得到" },
  off: { phonetic: "/ɔːf/", meaning: "离开；关闭" },
  third: { phonetic: "/θɜːrd/", meaning: "第三" },
  stop: { phonetic: "/stɑːp/", meaning: "停止" },
  really: { phonetic: "/ˈriːəli/", meaning: "真正地" },
  about: { phonetic: "/əˈbaʊt/", meaning: "关于；大约" },
  ten: { phonetic: "/ten/", meaning: "十" },
  minutes: { phonetic: "/ˈmɪnɪts/", meaning: "分钟" },
  walk: { phonetic: "/wɔːk/", meaning: "走" },
  fast: { phonetic: "/fæst/", meaning: "快的" },
  thanks: { phonetic: "/θæŋks/", meaning: "谢谢" },
  help: { phonetic: "/help/", meaning: "帮助" },
  safe: { phonetic: "/seɪf/", meaning: "安全的" },
  trip: { phonetic: "/trɪp/", meaning: "旅行" },
  check: { phonetic: "/tʃek/", meaning: "检查" },
  flight: { phonetic: "/flaɪt/", meaning: "航班" },
  tokyo: { phonetic: "/ˈtoʊkioʊ/", meaning: "东京" },
  passport: { phonetic: "/ˈpæspɔːrt/", meaning: "护照" },
  ticket: { phonetic: "/ˈtɪkɪt/", meaning: "票" },
  here: { phonetic: "/hɪr/", meaning: "这里" },
  need: { phonetic: "/niːd/", meaning: "需要" },
  backpack: { phonetic: "/ˈbækpæk/", meaning: "背包" },
  small: { phonetic: "/smɔːl/", meaning: "小的" },
  enough: { phonetic: "/ɪˈnʌf/", meaning: "足够的" },
  carry: { phonetic: "/ˈkæri/", meaning: "携带" },
  on: { phonetic: "/ɑːn/", meaning: "在……上" },
  window: { phonetic: "/ˈwɪndoʊ/", meaning: "窗户" },
  aisle: { phonetic: "/aɪl/", meaning: "过道" },
  seat: { phonetic: "/siːt/", meaning: "座位" },
  available: { phonetic: "/əˈveɪləbl/", meaning: "可用的" },
  certainly: { phonetic: "/ˈsɜːrtənli/", meaning: "当然" },
  boarding: { phonetic: "/ˈbɔːrdɪŋ/", meaning: "登机" },
  pass: { phonetic: "/pæs/", meaning: "通过；通行证" },
  starts: { phonetic: "/stɑːrts/", meaning: "开始" },
  gate: { phonetic: "/ɡeɪt/", meaning: "大门；登机口" },
  close: { phonetic: "/kloʊz/", meaning: "关闭" },
  departure: { phonetic: "/dɪˈpɑːrtʃər/", meaning: "出发" },
  got: { phonetic: "/ɡɑːt/", meaning: "得到（过去式）" },
  lounge: { phonetic: "/laʊndʒ/", meaning: "休息室" },
  use: { phonetic: "/juːz/", meaning: "使用" },
  access: { phonetic: "/ˈækses/", meaning: "进入；使用权" },
  star: { phonetic: "/stɑːr/", meaning: "星星" },
  alliance: { phonetic: "/əˈlaɪəns/", meaning: "联盟" },
  near: { phonetic: "/nɪr/", meaning: "靠近" },
  baggage: { phonetic: "/ˈbæɡɪdʒ/", meaning: "行李" },
  claim: { phonetic: "/kleɪm/", meaning: "认领；声称" },
  area: { phonetic: "/ˈeriə/", meaning: "区域" },
  follow: { phonetic: "/ˈfɑːloʊ/", meaning: "跟随" },
  signs: { phonetic: "/saɪnz/", meaning: "标志" },
  level: { phonetic: "/ˈlevəl/", meaning: "水平；楼层" },
  carousel: { phonetic: "/ˌkærəˈsel/", meaning: "旋转传送带" },
  number: { phonetic: "/ˈnʌmbər/", meaning: "数字" },
  currency: { phonetic: "/ˈkɜːrənsi/", meaning: "货币" },
  exchange: { phonetic: "/ɪksˈtʃeɪndʒ/", meaning: "交换；兑换" },
  desk: { phonetic: "/desk/", meaning: "桌子" },
  nearby: { phonetic: "/ˌnɪrˈbaɪ/", meaning: "附近" },
  yes: { phonetic: "/jes/", meaning: "是" },
  right: { phonetic: "/raɪt/", meaning: "右边；正确的" },
  next: { phonetic: "/nekst/", meaning: "下一个" },
  exit: { phonetic: "/ˈeɡzɪt/", meaning: "出口" },
  gates: { phonetic: "/ɡeɪts/", meaning: "大门（复数）" },
  left: { phonetic: "/left/", meaning: "左边" },
  reservation: { phonetic: "/ˌrezərˈveɪʃən/", meaning: "预订" },
  under: { phonetic: "/ˈʌndər/", meaning: "在……下面" },
  name: { phonetic: "/neɪm/", meaning: "名字" },
  smith: { phonetic: "/smɪθ/", meaning: "史密斯" },
  grand: { phonetic: "/ɡrænd/", meaning: "宏大的；豪华的" },
  hotel: { phonetic: "/hoʊˈtel/", meaning: "酒店" },
  pull: { phonetic: "/pʊl/", meaning: "拉" },
  file: { phonetic: "/faɪl/", meaning: "文件" },
  breakfast: { phonetic: "/ˈbrekfəst/", meaning: "早餐" },
  included: { phonetic: "/ɪnˈkluːdɪd/", meaning: "包括的" },
  room: { phonetic: "/ruːm/", meaning: "房间" },
  rate: { phonetic: "/reɪt/", meaning: "费率；速度" },
  complimentary: { phonetic: "/ˌkɑːmplɪˈmentəri/", meaning: "免费的；赠送的" },
  buffet: { phonetic: "/bəˈfeɪ/", meaning: "自助餐" },
  served: { phonetic: "/sɜːrvd/", meaning: "服务；上菜" },
  wonderful: { phonetic: "/ˈwʌndərfəl/", meaning: "精彩的" },
  wake: { phonetic: "/weɪk/", meaning: "醒来" },
  call: { phonetic: "/kɔːl/", meaning: "打电话；呼叫" },
  tomorrow: { phonetic: "/təˈmɑːroʊ/", meaning: "明天" },
  consider: { phonetic: "/kənˈsɪdər/", meaning: "考虑" },
  done: { phonetic: "/dʌn/", meaning: "完成" },
  key: { phonetic: "/kiː/", meaning: "钥匙；关键" },
  card: { phonetic: "/kɑːrd/", meaning: "卡片" },
  connect: { phonetic: "/kəˈnekt/", meaning: "连接" },
  network: { phonetic: "/ˈnetwɜːrk/", meaning: "网络" },
  password: { phonetic: "/ˈpæswɜːrd/", meaning: "密码" },
  back: { phonetic: "/bæk/", meaning: "后面；背部" },
  for: { phonetic: "/fɔːr/", meaning: "为了；给" },
  and: { phonetic: "/ænd/", meaning: "和；与" },
  this: { phonetic: "/ðɪs/", meaning: "这；这个" },
  that: { phonetic: "/ðæt/", meaning: "那；那个" },
  can: { phonetic: "/kæn/", meaning: "能够；可以" },
  like: { phonetic: "/laɪk/", meaning: "喜欢；像" },
  will: { phonetic: "/wɪl/", meaning: "将；会" },
  with: { phonetic: "/wɪð/", meaning: "和；用" },
  from: { phonetic: "/frʌm/", meaning: "从；来自" },
  where: { phonetic: "/wer/", meaning: "哪里" },
  let: { phonetic: "/let/", meaning: "让；允许" },
  all: { phonetic: "/ɔːl/", meaning: "全部；所有" },
  but: { phonetic: "/bʌt/", meaning: "但是" },
  there: { phonetic: "/ðer/", meaning: "那里" },
  would: { phonetic: "/wʊd/", meaning: "将会" },
  one: { phonetic: "/wʌn/", meaning: "一" },
  just: { phonetic: "/dʒʌst/", meaning: "只是；正好" },
  out: { phonetic: "/aʊt/", meaning: "出去；在外" },
  should: { phonetic: "/ʃʊd/", meaning: "应该" },
  make: { phonetic: "/meɪk/", meaning: "制作；使" },
  student: { phonetic: "/ˈstuːdənt/", meaning: "学生" },
  time: { phonetic: "/taɪm/", meaning: "时间" },
  before: { phonetic: "/bɪˈfɔːr/", meaning: "在...之前" },
  days: { phonetic: "/deɪz/", meaning: "天（复数）" },
  sign: { phonetic: "/saɪn/", meaning: "签名；标志" },
  any: { phonetic: "/ˈeni/", meaning: "任何" },
  does: { phonetic: "/dʌz/", meaning: "做（第三人称单数）" },
  month: { phonetic: "/mʌnθ/", meaning: "月" },
  online: { phonetic: "/ˈɒnlaɪn/", meaning: "在线" },
  twenty: { phonetic: "/ˈtwenti/", meaning: "二十" },
  after: { phonetic: "/ˈæftər/", meaning: "在...之后" },
  email: { phonetic: "/ˈiːmeɪl/", meaning: "电子邮件" },
  which: { phonetic: "/wɪtʃ/", meaning: "哪一个" },
  send: { phonetic: "/send/", meaning: "发送" },
  now: { phonetic: "/naʊ/", meaning: "现在" },
  team: { phonetic: "/tiːm/", meaning: "团队" },
  year: { phonetic: "/jɪr/", meaning: "年" },
  through: { phonetic: "/θruː/", meaning: "通过" },
  portal: { phonetic: "/ˈpɔːrtl/", meaning: "门户" },
  when: { phonetic: "/wen/", meaning: "什么时候" },
  front: { phonetic: "/frʌnt/", meaning: "前面" },
  know: { phonetic: "/noʊ/", meaning: "知道" },
  these: { phonetic: "/ðiːz/", meaning: "这些" },
  avoid: { phonetic: "/əˈvɔɪd/", meaning: "避免" },
  first: { phonetic: "/fɜːrst/", meaning: "第一" },
  rent: { phonetic: "/rent/", meaning: "租金；租" },
  keep: { phonetic: "/kiːp/", meaning: "保持" },
  week: { phonetic: "/wiːk/", meaning: "周" },
  last: { phonetic: "/læst/", meaning: "最后的；持续" },
  much: { phonetic: "/mʌtʃ/", meaning: "许多" },
  them: { phonetic: "/ðem/", meaning: "他们（宾格）" },
  course: { phonetic: "/kɔːrs/", meaning: "课程；过程" },
  campus: { phonetic: "/ˈkæmpəs/", meaning: "校园" },
  local: { phonetic: "/ˈloʊkl/", meaning: "当地的" },
  try: { phonetic: "/traɪ/", meaning: "尝试" },
  some: { phonetic: "/sʌm/", meaning: "一些" },
  everyone: { phonetic: "/ˈevriwʌn/", meaning: "每个人" },
  down: { phonetic: "/daʊn/", meaning: "向下" },
  four: { phonetic: "/fɔːr/", meaning: "四" },
  main: { phonetic: "/meɪn/", meaning: "主要的" },
  into: { phonetic: "/ˈɪntuː/", meaning: "进入" },
  long: { phonetic: "/lɔːŋ/", meaning: "长的" },
  day: { phonetic: "/deɪ/", meaning: "天" },
  book: { phonetic: "/bʊk/", meaning: "书；预订" },
  accept: { phonetic: "/əkˈsept/", meaning: "接受" },
  review: { phonetic: "/rɪˈvjuː/", meaning: "复习；审查" },
  current: { phonetic: "/ˈkɜːrənt/", meaning: "当前的" },
  upcoming: { phonetic: "/ʌpˈkʌmɪŋ/", meaning: "即将到来的" },
  renewal: { phonetic: "/rɪˈnuːəl/", meaning: "续签" },
  submit: { phonetic: "/səbˈmɪt/", meaning: "提交" },
  business: { phonetic: "/ˈbɪznəs/", meaning: "商业；商务" },
  drop: { phonetic: "/drɒp/", meaning: "放下；减少" },
  was: { phonetic: "/wʌz/", meaning: "是（过去式）" },
  physical: { phonetic: "/ˈfɪzɪkl/", meaning: "身体的；物理的" },
  prefer: { phonetic: "/prɪˈfɜːr/", meaning: "更喜欢" },
  sorry: { phonetic: "/ˈsɑːri/", meaning: "抱歉" },
  away: { phonetic: "/əˈweɪ/", meaning: "离开" },
  license: { phonetic: "/ˈlaɪsns/", meaning: "许可证；执照" },
  mind: { phonetic: "/maɪnd/", meaning: "介意；头脑" },
  include: { phonetic: "/ɪnˈkluːd/", meaning: "包括" },
  set: { phonetic: "/set/", meaning: "设置；放置" },
  perfect: { phonetic: "/ˈpɜːrfɪkt/", meaning: "完美的" },
  allowed: { phonetic: "/əˈlaʊd/", meaning: "允许的" },
  excited: { phonetic: "/ɪkˈsaɪtɪd/", meaning: "兴奋的" },
  depart: { phonetic: "/dɪˈpɑːrt/", meaning: "出发" },
  terminal: { phonetic: "/ˈtɜːrmɪnl/", meaning: "航站楼；终点站" },
  luggage: { phonetic: "/ˈlʌɡɪdʒ/", meaning: "行李" },
  keycard: { phonetic: "/ˈkiːkɑːrd/", meaning: "房卡；门禁卡" },
  maintenance: { phonetic: "/ˈmeɪntənəns/", meaning: "维护" },
  rental: { phonetic: "/ˈrentl/", meaning: "租赁" },
  collision: { phonetic: "/kəˈlɪʒən/", meaning: "碰撞" },
  coverage: { phonetic: "/ˈkʌvərɪdʒ/", meaning: "保险范围" },
  contract: { phonetic: "/ˈkɑːntrækt/", meaning: "合同" },
  slot: { phonetic: "/slɑːt/", meaning: "时间段；位置" },
  museum: { phonetic: "/mjuˈziːəm/", meaning: "博物馆" },
  souvenirs: { phonetic: "/ˌsuːvəˈnɪrz/", meaning: "纪念品" },
  artisan: { phonetic: "/ˈɑːrtɪzən/", meaning: "工匠" },
  pickpocket: { phonetic: "/ˈpɪkpɑːkɪt/", meaning: "扒手" },
  guided: { phonetic: "/ˈɡaɪdɪd/", meaning: "有导游的" },
  commentary: { phonetic: "/ˈkɒməntəri/", meaning: "解说" },
  session: { phonetic: "/ˈseʃən/", meaning: "场次；会议" },
  plaza: { phonetic: "/ˈplæzə/", meaning: "广场" },
  authentic: { phonetic: "/ɔːˈθentɪk/", meaning: "正宗的" },
  stalls: { phonetic: "/stɔːlz/", meaning: "摊位" },
  competitor: { phonetic: "/kəmˈpetɪtər/", meaning: "竞争对手" },
  warranty: { phonetic: "/ˈwɔːrənti/", meaning: "保修" },
  loyalty: { phonetic: "/ˈlɔɪəlti/", meaning: "忠诚；会员" },
  rewards: { phonetic: "/rɪˈwɔːrdz/", meaning: "奖励" },
  queue: { phonetic: "/kjuː/", meaning: "队列" },
  refund: { phonetic: "/ˈriːfʌnd/", meaning: "退款" },
  metrics: { phonetic: "/ˈmetrɪks/", meaning: "指标" },
  retention: { phonetic: "/rɪˈtenʃən/", meaning: "留存" },
  latency: { phonetic: "/ˈleɪtənsi/", meaning: "延迟" },
  downtime: { phonetic: "/ˈdaʊntaɪm/", meaning: "停机时间" },
  distributed: { phonetic: "/dɪˈstrɪbjuːtɪd/", meaning: "分布式的" },
  influencers: { phonetic: "/ˈɪnfluənsərz/", meaning: "影响者" },
  allocated: { phonetic: "/ˈæləkeɪtɪd/", meaning: "分配的" },
  tiered: { phonetic: "/tɪrd/", meaning: "分层的" },
  statements: { phonetic: "/ˈsteɪtmənts/", meaning: "报表" },
  uploaded: { phonetic: "/ˌʌpˈloʊdɪd/", meaning: "上传的" },
  receipts: { phonetic: "/rɪˈsiːts/", meaning: "收据" },
  incurred: { phonetic: "/ɪnˈkɜːrd/", meaning: "产生的" },
  beta: { phonetic: "/ˈbeɪtə/", meaning: "测试版" },
  testers: { phonetic: "/ˈtestərz/", meaning: "测试者" },
  intuitive: { phonetic: "/ɪnˈtuːɪtɪv/", meaning: "直观的" },
  optimization: { phonetic: "/ˌɒptɪmaɪˈzeɪʃən/", meaning: "优化" },
  momentum: { phonetic: "/moʊˈmentəm/", meaning: "势头" },
  terms: { phonetic: "/tɜːrmz/", meaning: "条款" },
  proposals: { phonetic: "/prəˈpoʊzəlz/", meaning: "提议" },
  reasonable: { phonetic: "/ˈriːznəbl/", meaning: "合理的" },
  director: { phonetic: "/dəˈrektər/", meaning: "总监" },
  addendum: { phonetic: "/əˈdendəm/", meaning: "附录" },
  reschedule: { phonetic: "/riːˈʃedjuːl/", meaning: "改期" },
  catering: { phonetic: "/ˈkeɪtərɪŋ/", meaning: "餐饮服务" },
  intensive: { phonetic: "/ɪnˈtensɪv/", meaning: "密集的" },
  sprint: { phonetic: "/sprɪnt/", meaning: "冲刺" },
  onboarding: { phonetic: "/ˈɑːnbɔːrdɪŋ/", meaning: "入职培训" },
  lease: { phonetic: "/liːs/", meaning: "租约" },
  viewing: { phonetic: "/ˈvjuːɪŋ/", meaning: "看房" },
  landlord: { phonetic: "/ˈlændlɔːrd/", meaning: "房东" },
  utilities: { phonetic: "/juːˈtɪlətiz/", meaning: "公用事业费" },
  refundable: { phonetic: "/rɪˈfʌndəbl/", meaning: "可退还的" },
  faucet: { phonetic: "/ˈfɔːsɪt/", meaning: "水龙头" },
  plumber: { phonetic: "/ˈplʌmbər/", meaning: "水管工" },
  renew: { phonetic: "/rɪˈnuː/", meaning: "续签" },
  signature: { phonetic: "/ˈsɪɡnətʃər/", meaning: "签名" },
  garbage: { phonetic: "/ˈɡɑːrbɪdʒ/", meaning: "垃圾" },
  disposal: { phonetic: "/dɪˈspoʊzəl/", meaning: "处理" },
  recyclables: { phonetic: "/riːˈsaɪkləblz/", meaning: "可回收物" },
  sorting: { phonetic: "/ˈsɔːrtɪŋ/", meaning: "分类" },
  reactivate: { phonetic: "/riːˈæktɪveɪt/", meaning: "重新激活" },
  demagnetized: { phonetic: "/diːˈmæɡnətaɪzd/", meaning: "消磁的" },
  "license plate": { phonetic: "/ˈlaɪsns pleɪt/", meaning: "车牌" },
  symptoms: { phonetic: "/ˈsɪmptəmz/", meaning: "症状" },
  throat: { phonetic: "/θroʊt/", meaning: "喉咙" },
  infection: { phonetic: "/ɪnˈfekʃən/", meaning: "感染" },
  dosage: { phonetic: "/ˈdoʊsɪdʒ/", meaning: "剂量" },
  dietary: { phonetic: "/ˈdaɪətəri/", meaning: "饮食的" },
  restrictions: { phonetic: "/rɪˈstrɪkʃənz/", meaning: "限制" },
  twisted: { phonetic: "/twɪstɪd/", meaning: "扭伤的" },
  fracture: { phonetic: "/ˈfræktʃər/", meaning: "骨折" },
  swelling: { phonetic: "/ˈswelɪŋ/", meaning: "肿胀" },
  crutches: { phonetic: "/ˈkrʌtʃɪz/", meaning: "拐杖" },
  refill: { phonetic: "/riːˈfɪl/", meaning: "续药" },
  stable: { phonetic: "/ˈsteɪbl/", meaning: "稳定的" },
  reminder: { phonetic: "/rɪˈmaɪndər/", meaning: "提醒" },
  insomnia: { phonetic: "/ɪnˈsɒmniə/", meaning: "失眠" },
  herbal: { phonetic: "/ˈhɜːrbl/", meaning: "草本的" },
  overseas: { phonetic: "/ˌoʊvərˈsiːz/", meaning: "海外的" },
  typhoid: { phonetic: "/ˈtaɪfɔɪd/", meaning: "伤寒" },
  hepatitis: { phonetic: "/ˌhepəˈtaɪtɪs/", meaning: "肝炎" },
  "side effects": { phonetic: "/saɪd ɪˈfekts/", meaning: "副作用" },
  lozenges: { phonetic: "/ˈlɒzɪndʒɪz/", meaning: "润喉片" },
  "nasal spray": { phonetic: "/ˈneɪzəl spreɪ/", meaning: "鼻喷剂" },
  congested: { phonetic: "/kənˈdʒestɪd/", meaning: "鼻塞的" },
  nostril: { phonetic: "/ˈnɒstrɪl/", meaning: "鼻孔" },
  savings: { phonetic: "/ˈseɪvɪŋz/", meaning: "储蓄" },
  debit: { phonetic: "/ˈdebɪt/", meaning: "借记" },
  wire: { phonetic: "/waɪr/", meaning: "电汇" },
  clearance: { phonetic: "/ˈklɪərəns/", meaning: "清算" },
  advance: { phonetic: "/ədˈvæns/", meaning: "预支" },
  "express-shipped": { phonetic: "/ɪkˈspres ʃɪpt/", meaning: "快递寄送" },
  unauthorized: { phonetic: "/ʌnˈɔːθəraɪzd/", meaning: "未授权的" },
  mortgage: { phonetic: "/ˈmɔːrɡɪdʒ/", meaning: "抵押贷款" },
  income: { phonetic: "/ˈɪnkʌm/", meaning: "收入" },
  verification: { phonetic: "/ˌverɪfɪˈkeɪʃən/", meaning: "验证" },
  withdrawal: { phonetic: "/wɪðˈdrɔːəl/", meaning: "提取" },
  "cash-back": { phonetic: "/kæʃ bæk/", meaning: "返现" },
  criteria: { phonetic: "/kraɪˈtɪəriə/", meaning: "标准" },
  deductible: { phonetic: "/dɪˈdʌktəbl/", meaning: "可抵扣的" },
  diversified: { phonetic: "/daɪˈvɜːrsɪfaɪd/", meaning: "多元化的" },
  dividend: { phonetic: "/ˈdɪvɪdend/", meaning: "股息" },
  tolerance: { phonetic: "/ˈtɒlərəns/", meaning: "承受力" },
  certified: { phonetic: "/ˈsɜːrtɪfaɪd/", meaning: "持证的" },
  advisor: { phonetic: "/ədˈvaɪzər/", meaning: "顾问" },
  mutual: { phonetic: "/ˈmjuːtʃuəl/", meaning: "共同的" },
  commission: { phonetic: "/kəˈmɪʃən/", meaning: "佣金" },
  wholesale: { phonetic: "/ˈhoʊlseɪl/", meaning: "批发的" },
  provisional: { phonetic: "/prəˈvɪʒənl/", meaning: "临时的" },
  fraud: { phonetic: "/frɔːd/", meaning: "欺诈" },
  "instant-issue": { phonetic: "/ˈɪnstənt ɪʃuː/", meaning: "即时发行的" },
  casual: { phonetic: "/ˈkæʒuəl/", meaning: "休闲的" },
  fitting: { phonetic: "/ˈfɪtɪŋ/", meaning: "试衣间" },
  produce: { phonetic: "/ˈproʊduːs/", meaning: "农产品" },
  orchard: { phonetic: "/ˈɔːrtʃərd/", meaning: "果园" },
  "sci-fi": { phonetic: "/ˈsaɪ faɪ/", meaning: "科幻" },
  trilogy: { phonetic: "/ˈtrɪlədʒi/", meaning: "三部曲" },
  boxed: { phonetic: "/bɒkst/", meaning: "盒装的" },
  bestseller: { phonetic: "/ˈbestseller/", meaning: "畅销书" },
  "gift-wrap": { phonetic: "/ɡɪft ræp/", meaning: "礼品包装" },
  stacked: { phonetic: "/stækt/", meaning: "叠加的" },
  accumulate: { phonetic: "/əˈkjuːmjəleɪt/", meaning: "积累" },
  "half-price": { phonetic: "/hæf praɪs/", meaning: "半价" },
  deduct: { phonetic: "/dɪˈdʌkt/", meaning: "扣除" },
  barcode: { phonetic: "/ˈbɑːrkoʊd/", meaning: "条形码" },
  tote: { phonetic: "/toʊt/", meaning: "手提袋" },
  intact: { phonetic: "/ɪnˈtækt/", meaning: "完好无损的" },
  threshold: { phonetic: "/ˈθreʃhoʊld/", meaning: "门槛" },
  shipping: { phonetic: "/ˈʃɪpɪŋ/", meaning: "运输" },
  overnight: { phonetic: "/ˌoʊvərˈnaɪt/", meaning: "隔夜的" },
  "real-time": { phonetic: "/ˈriːəl taɪm/", meaning: "实时的" },
  GPS: { phonetic: "/ˌdʒiː piː ˈes/", meaning: "全球定位系统" },
  tracking: { phonetic: "/ˈtrækɪŋ/", meaning: "追踪" },
  luxury: { phonetic: "/ˈlʌkʃəri/", meaning: "奢侈的" },
  leather: { phonetic: "/ˈleðər/", meaning: "皮革" },
  handbag: { phonetic: "/ˈhændbæɡ/", meaning: "手提包" },
  handcrafted: { phonetic: "/ˈhændkræftɪd/", meaning: "手工制作的" },
  exquisite: { phonetic: "/ɪkˈskwɪzɪt/", meaning: "精美的" },
  genuine: { phonetic: "/ˈdʒenjuɪn/", meaning: "真正的" },
  calfskin: { phonetic: "/ˈkæfskɪn/", meaning: "小牛皮" },
  "full-grain": { phonetic: "/fʊl ɡreɪn/", meaning: "全粒面的" },
  stamped: { phonetic: "/stæmpt/", meaning: "盖章的" },
  discrepancy: { phonetic: "/dɪsˈkrepənsi/", meaning: "差异" },
  resolve: { phonetic: "/rɪˈzɒlv/", meaning: "解决" },
  transfer: { phonetic: "/ˈtrænsfɜːr/", meaning: "换乘" },
  peak: { phonetic: "/piːk/", meaning: "高峰的" },
  rush: { phonetic: "/rʌʃ/", meaning: "高峰" },
  "off-peak": { phonetic: "/ɒf piːk/", meaning: "非高峰的" },
  shelter: { phonetic: "/ˈʃeltər/", meaning: "候车亭" },
  signpost: { phonetic: "/ˈsaɪnpoʊst/", meaning: "站牌" },
  hail: { phonetic: "/heɪl/", meaning: "招手" },
  southbound: { phonetic: "/ˈsaʊθbaʊnd/", meaning: "南行的" },
  platform: { phonetic: "/ˈplætfɔːrm/", meaning: "站台" },
  concourse: { phonetic: "/ˈkɒŋkɔːrs/", meaning: "大厅" },
  equipped: { phonetic: "/ɪˈkwɪpt/", meaning: "配备的" },
  climate: { phonetic: "/ˈklaɪmət/", meaning: "气候" },
  precisely: { phonetic: "/prɪˈsaɪsli/", meaning: "精确地" },
  unlimited: { phonetic: "/ʌnˈlɪmɪtɪd/", meaning: "无限的" },
  automated: { phonetic: "/ˈɔːtəmeɪtɪd/", meaning: "自动的" },
  vending: { phonetic: "/ˈvendɪŋ/", meaning: "售货的" },
  coins: { phonetic: "/kɔɪnz/", meaning: "硬币" },
  reader: { phonetic: "/ˈriːdər/", meaning: "读卡器" },
  sensor: { phonetic: "/sensər/", meaning: "感应器" },
  QR: { phonetic: "/ˌdʒuː ˈɑːr/", meaning: "二维码" },
  discounted: { phonetic: "/ˈdɪskaʊntɪd/", meaning: "打折的" },
  fare: { phonetic: "/fer/", meaning: "票价" },
  citizens: { phonetic: "/ˈsɪtɪzənz/", meaning: "公民" },
  concession: { phonetic: "/kənˈseʃən/", meaning: "优惠" },
  reserved: { phonetic: "/rɪˈzɜːrvd/", meaning: "预留的" },
  unreserved: { phonetic: "/ˌʌnrɪˈzɜːrvd/", meaning: "非预留的" },
  coach: { phonetic: "/koʊtʃ/", meaning: "车厢" },
  compartment: { phonetic: "/kəmˈpɑːrtmənt/", meaning: "隔间" },
  racks: { phonetic: "/ræks/", meaning: "架子" },
  dining: { phonetic: "/ˈdaɪnɪŋ/", meaning: "用餐的" },
  cafeteria: { phonetic: "/ˌkæfəˈtɪəriə/", meaning: "自助餐厅" },
  attendants: { phonetic: "/əˈtendənts/", meaning: "乘务员" },
  trolley: { phonetic: "/ˈtrɒli/", meaning: "手推车" },
  conductor: { phonetic: "/kənˈdʌktər/", meaning: "列车员" },
  rideshare: { phonetic: "/ˈraɪdʃer/", meaning: "网约车" },
  estimated: { phonetic: "/ˈestɪmeɪtɪd/", meaning: "预计的" },
  pickup: { phonetic: "/ˈpɪkʌp/", meaning: "接载" },
  trunk: { phonetic: "/trʌŋk/", meaning: "后备箱" },
  toll: { phonetic: "/toʊl/", meaning: "过路费" },
  signal: { phonetic: "/ˈsɪɡnəl/", meaning: "信号" },
  breakdown: { phonetic: "/ˈbreɪkdaʊn/", meaning: "故障" },
  detour: { phonetic: "/ˈdiːtʊər/", meaning: "绕行" },
  bypass: { phonetic: "/ˈbaɪpɑːs/", meaning: "绕过" },
  suspended: { phonetic: "/səˈspendɪd/", meaning: "暂停的" },
  "proof-of-delay": { phonetic: "/pruːf əv deɪ/", meaning: "晚点证明" },
  lost: { phonetic: "/lɔːst/", meaning: "丢失的" },
  found: { phonetic: "/faʊnd/", meaning: "找到的" },
  disembarked: { phonetic: "/dɪsˈembɑːrkt/", meaning: "下车的" },
  unclaimed: { phonetic: "/ʌnˈkleɪmd/", meaning: "无人认领的" },
  belongings: { phonetic: "/bɪˈlɒŋɪŋz/", meaning: "物品" },
  dockless: { phonetic: "/ˈdɒkləs/", meaning: "无桩的" },
  handlebars: { phonetic: "/ˈhændlbɑːrz/", meaning: "车把" },
  designated: { phonetic: "/ˈdezɪɡneɪtɪd/", meaning: "指定的" },
  zone: { phonetic: "/zoʊn/", meaning: "区域" },
  protected: { phonetic: "/prəˈtektɪd/", meaning: "受保护的" },
  hourly: { phonetic: "/ˈaʊərli/", meaning: "每小时的" },
  "pedal-assist": { phonetic: "/ˈpedl əˌsɪst/", meaning: "助力的" },
  helmet: { phonetic: "/ˈhelmɪt/", meaning: "头盔" },
  mandatory: { phonetic: "/ˈmændətɔːri/", meaning: "强制的" },
  minors: { phonetic: "/ˈmaɪnərz/", meaning: "未成年人" },
  harbor: { phonetic: "/ˈhɑːrbər/", meaning: "港口" },
  illuminated: { phonetic: "/ɪˈluːmɪneɪtɪd/", meaning: "照明的" },
  expire: { phonetic: "/ɪkˈspaɪr/", meaning: "过期" },
  expedited: { phonetic: "/ˈekspədaɪtɪd/", meaning: "加急的" },
  "walk-in": { phonetic: "/ˈwɔːk ɪn/", meaning: "免预约的" },
  citizenship: { phonetic: "/ˈsɪtɪzənʃɪp/", meaning: "公民身份" },
  assessment: { phonetic: "/əˈsesmənt/", meaning: "评估" },
  appeal: { phonetic: "/əˈpiːl/", meaning: "申诉" },
  postmarked: { phonetic: "/ˈpoʊstmɑːrkt/", meaning: "盖邮戳的" },
  installment: { phonetic: "/ɪnˈstɔːlmənt/", meaning: "分期付款" },
  accrue: { phonetic: "/əˈkruː/", meaning: "累积" },
  statutory: { phonetic: "/ˈstætʃʊtɔːri/", meaning: "法定的" },
  waived: { phonetic: "/weɪvd/", meaning: "豁免的" },
  entity: { phonetic: "/ˈentəti/", meaning: "实体" },
  incorporate: { phonetic: "/ɪnˈkɔːrpəreɪt/", meaning: "注册公司" },
  storefront: { phonetic: "/ˈstɔːrfrʌnt/", meaning: "门店" },
  permits: { phonetic: "/ˈpɜːrmɪts/", meaning: "许可证" },
  sanitation: { phonetic: "/ˌsænɪˈteɪʃən/", meaning: "卫生" },
  supporting: { phonetic: "/səˈpɔːrtɪŋ/", meaning: "支持性的" },
  structural: { phonetic: "/ˈstrʌktʃərəl/", meaning: "结构的" },
  blueprints: { phonetic: "/ˈbluːprɪnts/", meaning: "蓝图" },
  diagrams: { phonetic: "/ˈdaɪəɡræmz/", meaning: "图表" },
  scaled: { phonetic: "/skeɪld/", meaning: "按比例的" },
  boundary: { phonetic: "/ˈbaʊndəri/", meaning: "边界" },
  zoning: { phonetic: "/ˈzoʊnɪŋ/", meaning: "规划" },
  setbacks: { phonetic: "/ˈsetbæks/", meaning: "退界" },
  inspector: { phonetic: "/ɪnˈspektər/", meaning: "检查员" },
  corrections: { phonetic: "/kəˈrekʃənz/", meaning: "整改" },
  variance: { phonetic: "/ˈveəriəns/", meaning: "变更许可" },
  ordinances: { phonetic: "/ˈɔːrdɪnənsɪz/", meaning: "条例" },
  vital: { phonetic: "/ˈvaɪtl/", meaning: "重要的；生命的" },
  immediate: { phonetic: "/ɪˈmiːdiət/", meaning: "直系的" },
  apostille: { phonetic: "/əˈpɒstɪl/", meaning: "海牙认证" },
  probate: { phonetic: "/ˈproʊbeɪt/", meaning: "遗嘱检验" },
  disability: { phonetic: "/ˌdɪsəˈbɪlɪti/", meaning: "伤残" },
  disbursement: { phonetic: "/dɪsˈbɜːrsmənt/", meaning: "发放" },
  precinct: { phonetic: "/ˈpriːsɪŋkt/", meaning: "选区" },
  voter: { phonetic: "/ˈvoʊtər/", meaning: "选民" },
  polling: { phonetic: "/ˈpoʊlɪŋ/", meaning: "投票的" },
  assigned: { phonetic: "/əˈsaɪnd/", meaning: "指定的" },
  interactive: { phonetic: "/ˌɪntərˈæktɪv/", meaning: "交互的" },
  council: { phonetic: "/ˈkaʊnsl/", meaning: "议会" },
  citation: { phonetic: "/saɪˈteɪʃən/", meaning: "罚单" },
  civil: { phonetic: "/ˈsɪvl/", meaning: "民事的" },
  infractions: { phonetic: "/ɪnˈfrækʃənz/", meaning: "违规行为" },
  defensive: { phonetic: "/dɪˈfensɪv/", meaning: "防御性的" },
  dismiss: { phonetic: "/dɪsˈmɪs/", meaning: "撤销" },
  fines: { phonetic: "/faɪnz/", meaning: "罚款" },
  penalties: { phonetic: "/ˈpenəltiz/", meaning: "处罚" },
  suspension: { phonetic: "/səˈspenʃən/", meaning: "吊销" },
  refuse: { phonetic: "/ˈrefjuːs/", meaning: "垃圾" },
  curbside: { phonetic: "/ˈkɜːrbsaɪd/", meaning: "路边的" },
  trimming: { phonetic: "/ˈtrɪmɪŋ/", meaning: "修剪" },
  "low-income": { phonetic: "/loʊ ˈɪnkʌm/", meaning: "低收入的" },
  abatement: { phonetic: "/əˈbeɪtmənt/", meaning: "控制" },
  lodge: { phonetic: "/lɒdʒ/", meaning: "提出" },
  "non-emergency": { phonetic: "/nɒn ɪˈmɜːrdʒənsi/", meaning: "非紧急的" },
  overgrown: { phonetic: "/ˌoʊvərˈɡroʊn/", meaning: "过长的" },
  "non-compliance": { phonetic: "/nɒn kəmˈplaɪəns/", meaning: "不合规" },
  rabies: { phonetic: "/ˈreɪbiːz/", meaning: "狂犬病" },
  handler: { phonetic: "/ˈhændlər/", meaning: "从业人员" },
};

export function getWordDefinition(word: string): WordDefinition {
  const clean = cleanLookupWord(word);
  return WORDS[clean] ?? { phonetic: "", meaning: "暂未找到释义" };
}

export function cleanLookupWord(word: string) {
  return word.toLowerCase().replace(/[^a-z' -]/g, "").replace(/\s+/g, " ").trim();
}

const remoteCache = new Map<string, WordDefinition>();

export async function lookupWordDefinition(word: string): Promise<WordDefinition> {
  const clean = cleanLookupWord(word);
  const local = getWordDefinition(clean);
  if (!clean) return local;
  const cached = remoteCache.get(clean);
  if (cached) return cached;
  try {
    const response = await fetch(`https://api.dictionaryapi.dev/api/v2/entries/en/${encodeURIComponent(clean)}`);
    if (!response.ok) return local;
    const payload = await response.json() as Array<{
      phonetic?: string;
      phonetics?: Array<{ text?: string; audio?: string }>;
      meanings?: Array<{ definitions?: Array<{ definition?: string }> }>;
    }>;
    const entry = payload[0];
    
    // 优先获取音标：先尝试 phonetic 字段，再从 phonetics 数组中查找有 text 的项
    const phonetic = entry?.phonetic ?? entry?.phonetics?.find((item) => item.text)?.text ?? local.phonetic;
    
    // 获取英文释义
    const englishMeaning = entry?.meanings?.flatMap((meaning) => meaning.definitions ?? []).map((item) => item.definition).find(Boolean);
    
    if (!englishMeaning) return { phonetic, meaning: local.meaning };
    
    try {
      // 翻译英文释义为中文
      const translationResponse = await fetch(`https://api.mymemory.translated.net/get?q=${encodeURIComponent(englishMeaning)}&langpair=en|zh-CN`);
      const translationPayload = await translationResponse.json() as { responseData?: { translatedText?: string } };
      const result = { phonetic, meaning: translationPayload.responseData?.translatedText?.trim() || local.meaning };
      remoteCache.set(clean, result);
      return result;
    } catch {
      return { phonetic, meaning: local.meaning };
    }
  } catch {
    return local;
  }
}